//HintName: IPrimitiveArray.g.cs
// <auto-generated />
#pragma warning disable
namespace Fluentish.Injectable.MethodReturnTests
{
    /// <inheritdoc cref="global::MethodReturnTests.PrimitiveArray"/>
    public interface IPrimitiveArray
    {
        /// <inheritdoc cref="global::MethodReturnTests.PrimitiveArray.Test"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        object[] Test();

    }
}
#pragma warning restore
