//HintName: PrimitiveArray.g.cs
// <auto-generated />
#pragma warning disable
namespace Fluentish.Injectable.MethodReturnTests
{
    /// <inheritdoc cref="global::MethodReturnTests.PrimitiveArray"/>
    [global::System.Diagnostics.DebuggerStepThrough]
    public class PrimitiveArrayService: IPrimitiveArray
    {
        /// <inheritdoc cref="global::MethodReturnTests.PrimitiveArray.Test"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public object[] Test() => global::MethodReturnTests.PrimitiveArray.Test();
    }
}
#pragma warning restore
