//HintName: NullableValueType.g.cs
// <auto-generated />
#nullable enable
#pragma warning disable
namespace Fluentish.Injectable.MethodReturnTests
{
    /// <inheritdoc cref="global::MethodReturnTests.NullableValueType"/>
    [global::System.Diagnostics.DebuggerStepThrough]
    public class NullableValueTypeService: INullableValueType
    {
        /// <inheritdoc cref="global::MethodReturnTests.NullableValueType.Test"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public global::System.Nullable<global::MethodReturnTests.Example> Test() => global::MethodReturnTests.NullableValueType.Test();
    }
}
#pragma warning restore
