//HintName: IReturnSugarTuple.g.cs
// <auto-generated />
#pragma warning disable
namespace Fluentish.Injectable.PropertyReturnTypeTests
{
    /// <inheritdoc cref="global::PropertyReturnTypeTests.ReturnSugarTuple"/>
    public interface IReturnSugarTuple
    {
        /// <inheritdoc cref="global::PropertyReturnTypeTests.ReturnSugarTuple.Test"/>
        (global::PropertyReturnTypeTests.Example left, global::PropertyReturnTypeTests.Example right) Test { get; set; }

    }
}
#pragma warning restore
