//HintName: ReturnSugarTuple.g.cs
// <auto-generated />
#pragma warning disable
namespace Fluentish.Injectable.PropertyReturnTypeTests
{
    /// <inheritdoc cref="global::PropertyReturnTypeTests.ReturnSugarTuple"/>
    [global::System.Diagnostics.DebuggerStepThrough]
    public class ReturnSugarTupleService: IReturnSugarTuple
    {
        /// <inheritdoc cref="global::PropertyReturnTypeTests.ReturnSugarTuple.Test"/>
        public (global::PropertyReturnTypeTests.Example left, global::PropertyReturnTypeTests.Example right) Test
        {
            get => global::PropertyReturnTypeTests.ReturnSugarTuple.Test;
            set => global::PropertyReturnTypeTests.ReturnSugarTuple.Test = value;
        }

    }
}
#pragma warning restore
