//HintName: ReturnPrimitive.g.cs
// <auto-generated />
#pragma warning disable
namespace Fluentish.Injectable.FieldReturnTypeTests
{
    /// <inheritdoc cref="global::FieldReturnTypeTests.ReturnPrimitive"/>
    [global::System.Diagnostics.DebuggerStepThrough]
    public class ReturnPrimitiveService: IReturnPrimitive
    {
        /// <inheritdoc cref="global::FieldReturnTypeTests.ReturnPrimitive.Test"/>
        public int Test
        {
            get => global::FieldReturnTypeTests.ReturnPrimitive.Test;
            set => global::FieldReturnTypeTests.ReturnPrimitive.Test = value;
        }
    }
}
#pragma warning restore
