//HintName: IProperty.g.cs
// <auto-generated />
#pragma warning disable
namespace Fluentish.Injectable.MemberNameKeywordCollisionTests
{
    /// <inheritdoc cref="global::MemberNameKeywordCollisionTests.Property"/>
    public interface IProperty
    {
        /// <inheritdoc cref="global::MemberNameKeywordCollisionTests.Property.@event"/>
        int @event { get; set; }

    }
}
#pragma warning restore
