//HintName: Property.g.cs
// <auto-generated />
#pragma warning disable
namespace Fluentish.Injectable.MemberNameKeywordCollisionTests
{
    /// <inheritdoc cref="global::MemberNameKeywordCollisionTests.Property"/>
    [global::System.Diagnostics.DebuggerStepThrough]
    public class PropertyService : IProperty
    {
        /// <inheritdoc cref="global::MemberNameKeywordCollisionTests.Property.@event"/>
        public int @event
        {
            get => global::MemberNameKeywordCollisionTests.Property.@event;
            set => global::MemberNameKeywordCollisionTests.Property.@event = value;
        }

    }
}
#pragma warning restore
