//HintName: ReturnSugarTuple.g.cs
// <auto-generated />
#pragma warning disable
namespace Fluentish.Injectable.FieldReturnTypeTests
{
    /// <inheritdoc cref="global::FieldReturnTypeTests.ReturnSugarTuple"/>
    [global::System.Diagnostics.DebuggerStepThrough]
    public class ReturnSugarTupleService : IReturnSugarTuple
    {
        /// <inheritdoc cref="global::FieldReturnTypeTests.ReturnSugarTuple.Test"/>
        public (string left, object right) Test
        {
            get => global::FieldReturnTypeTests.ReturnSugarTuple.Test;
            set => global::FieldReturnTypeTests.ReturnSugarTuple.Test = value;
        }
    }
}
#pragma warning restore
