//HintName: IGenericTypeArgument.g.cs
// <auto-generated />
#pragma warning disable
namespace Fluentish.Injectable.GenericMethodTests
{
    /// <inheritdoc cref="global::GenericMethodTests.GenericTypeArgument"/>
    public interface IGenericTypeArgument
    {
        /// <inheritdoc cref="global::GenericMethodTests.GenericTypeArgument.Test"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        void Test<TType>();

    }
}
#pragma warning restore
