//HintName: GenericTypeArgument.g.cs
// <auto-generated />
#pragma warning disable
namespace Fluentish.Injectable.GenericMethodTests
{
    /// <inheritdoc cref="global::GenericMethodTests.GenericTypeArgument"/>
    [global::System.Diagnostics.DebuggerStepThrough]
    public class GenericTypeArgumentService : IGenericTypeArgument
    {
        /// <inheritdoc cref="global::GenericMethodTests.GenericTypeArgument.Test"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public void Test<TType>()
             => global::GenericMethodTests.GenericTypeArgument.Test<TType>();
    }
}
#pragma warning restore
