//HintName: IStructNullable.g.cs
// <auto-generated />
#nullable enable
#pragma warning disable
namespace Fluentish.Injectable.MethodReturnTests
{
    /// <inheritdoc cref="global::MethodReturnTests.StructNullable"/>
    public interface IStructNullable
    {
        /// <inheritdoc cref="global::MethodReturnTests.StructNullable.Test"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        global::System.Nullable<global::MethodReturnTests.Example> Test();
    }
}
#pragma warning restore
