//HintName: TupleClassPrimitive.g.cs
// <auto-generated />
#pragma warning disable
namespace Fluentish.Injectable.MethodReturnTests
{
    /// <inheritdoc cref="global::MethodReturnTests.TupleClassPrimitive"/>
    [global::System.Diagnostics.DebuggerStepThrough]
    public class TupleClassPrimitiveService : ITupleClassPrimitive
    {
        /// <inheritdoc cref="global::MethodReturnTests.TupleClassPrimitive.Test"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public global::System.Tuple<global::MethodReturnTests.Example, global::MethodReturnTests.Example> Test()
             => global::MethodReturnTests.TupleClassPrimitive.Test();
    }
}
#pragma warning restore
