//HintName: PrivateEvent.g.cs
// <auto-generated />
#pragma warning disable
namespace Fluentish.Injectable.EventAccessibilityTests
{
    /// <inheritdoc cref="global::EventAccessibilityTests.PrivateEvent"/>
    [global::System.Diagnostics.DebuggerStepThrough]
    public class PrivateEventService : IPrivateEvent
    {
    }
}
#pragma warning restore
