//HintName: TupleClass.g.cs
// <auto-generated />
#pragma warning disable
namespace Fluentish.Injectable.MethodReturnTests
{
    /// <inheritdoc cref="global::MethodReturnTests.TupleClass"/>
    [global::System.Diagnostics.DebuggerStepThrough]
    public class TupleClassService : ITupleClass
    {
        /// <inheritdoc cref="global::MethodReturnTests.TupleClass.Test"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public global::System.Tuple<string, object> Test() => global::MethodReturnTests.TupleClass.Test();
    }
}
#pragma warning restore
