//HintName: IReturnPrimitive.g.cs
// <auto-generated />
#pragma warning disable
namespace Fluentish.Injectable.ConstReturnTypeTests
{
    /// <inheritdoc cref="global::ConstReturnTypeTests.ReturnPrimitive"/>
    public interface IReturnPrimitive
    {
        /// <inheritdoc cref="global::ConstReturnTypeTests.ReturnPrimitive.Test"/>
        int Test { get; }
    }
}
#pragma warning restore
