//HintName: IList.g.cs
// <auto-generated />
#pragma warning disable
namespace Fluentish.Injectable.MethodReturnTests
{
    /// <inheritdoc cref="global::MethodReturnTests.List"/>
    public interface IList
    {
        /// <inheritdoc cref="global::MethodReturnTests.List.Test"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        global::System.Collections.Generic.List<string> Test();
    }
}
#pragma warning restore
