//HintName: ICustomPrefix.g.cs
// <auto-generated />
#pragma warning disable
namespace CustomPrefix.NamespacePrefixTests
{
    /// <inheritdoc cref="global::NamespacePrefixTests.CustomPrefix"/>
    public interface ICustomPrefix
    {
        /// <inheritdoc cref="global::NamespacePrefixTests.CustomPrefix.Test"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        void Test();

    }
}
#pragma warning restore
