//HintName: CustomPrefix.g.cs
// <auto-generated />
#pragma warning disable
namespace CustomPrefix.NamespacePrefixTests
{
    /// <inheritdoc cref="global::NamespacePrefixTests.CustomPrefix"/>
    [global::System.Diagnostics.DebuggerStepThrough]
    public class CustomPrefixService : ICustomPrefix
    {
        /// <inheritdoc cref="global::NamespacePrefixTests.CustomPrefix.Test"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public void Test()
             => global::NamespacePrefixTests.CustomPrefix.Test();
    }
}
#pragma warning restore
