//HintName: ITuple.g.cs
// <auto-generated />
#pragma warning disable
namespace Fluentish.Injectable.MethodReturnTests
{
    /// <inheritdoc cref="global::MethodReturnTests.Tuple"/>
    public interface ITuple
    {
        /// <inheritdoc cref="global::MethodReturnTests.Tuple.Test"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        (global::MethodReturnTests.Example left, global::MethodReturnTests.Example right) Test();
    }
}
#pragma warning restore
