//HintName: Tuple.g.cs
// <auto-generated />
#pragma warning disable
namespace Fluentish.Injectable.MethodReturnTests
{
    /// <inheritdoc cref="global::MethodReturnTests.Tuple"/>
    [global::System.Diagnostics.DebuggerStepThrough]
    public class TupleService : ITuple
    {
        /// <inheritdoc cref="global::MethodReturnTests.Tuple.Test"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public (global::MethodReturnTests.Example left, global::MethodReturnTests.Example right) Test()
             => global::MethodReturnTests.Tuple.Test();
    }
}
#pragma warning restore
