//HintName: IMethodParameter.g.cs
// <auto-generated />
#pragma warning disable
namespace Fluentish.Injectable.MemberNameKeywordCollisionTests
{
    /// <inheritdoc cref="global::MemberNameKeywordCollisionTests.MethodParameter"/>
    public interface IMethodParameter
    {
        /// <inheritdoc cref="global::MemberNameKeywordCollisionTests.MethodParameter.Test"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        void Test(int @event);

    }
}
#pragma warning restore
