//HintName: MethodParameter.g.cs
// <auto-generated />
#pragma warning disable
namespace Fluentish.Injectable.MemberNameKeywordCollisionTests
{
    /// <inheritdoc cref="global::MemberNameKeywordCollisionTests.MethodParameter"/>
    [global::System.Diagnostics.DebuggerStepThrough]
    public class MethodParameterService : IMethodParameter
    {
        /// <inheritdoc cref="global::MemberNameKeywordCollisionTests.MethodParameter.Test"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public void Test(int @event)
            => global::MemberNameKeywordCollisionTests.MethodParameter.Test(@event);

    }
}
#pragma warning restore
