//HintName: Empty.g.cs
// <auto-generated />
#pragma warning disable
/// <inheritdoc cref="global::NamespaceConstTests.Empty"/>
[global::System.Diagnostics.DebuggerStepThrough]
public class EmptyService : IEmpty
{
    /// <inheritdoc cref="global::NamespaceConstTests.Empty.Test"/>
    [global::System.Diagnostics.DebuggerStepThrough]
    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public void Test() => global::NamespaceConstTests.Empty.Test();
}
#pragma warning restore
