//HintName: IEmpty.g.cs
// <auto-generated />
#pragma warning disable
/// <inheritdoc cref="global::NamespaceConstTests.Empty"/>
public interface IEmpty
{
    /// <inheritdoc cref="global::NamespaceConstTests.Empty.Test"/>
    [global::System.Diagnostics.DebuggerStepThrough]
    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    void Test();

}
#pragma warning restore
