//HintName: IGenericTypeArgumentConstraintValueType.g.cs
// <auto-generated />
#pragma warning disable
namespace Fluentish.Injectable.GenericMethodTests
{
    /// <inheritdoc cref="global::GenericMethodTests.GenericTypeArgumentConstraintValueType"/>
    public interface IGenericTypeArgumentConstraintValueType
    {
        /// <inheritdoc cref="global::GenericMethodTests.GenericTypeArgumentConstraintValueType.Test"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        void Test<TType>()
            where TType : struct;
    }
}
#pragma warning restore
