//HintName: ReturnNullableReferenceType.g.cs
// <auto-generated />
#nullable enable
#pragma warning disable
namespace Fluentish.Injectable.PropertyReturnTypeTests
{
    /// <inheritdoc cref="global::PropertyReturnTypeTests.ReturnNullableReferenceType"/>
    [global::System.Diagnostics.DebuggerStepThrough]
    public class ReturnNullableReferenceTypeService: IReturnNullableReferenceType
    {
        /// <inheritdoc cref="global::PropertyReturnTypeTests.ReturnNullableReferenceType.Test"/>
        public global::PropertyReturnTypeTests.Example? Test
        {
            get => global::PropertyReturnTypeTests.ReturnNullableReferenceType.Test;
            set => global::PropertyReturnTypeTests.ReturnNullableReferenceType.Test = value;
        }

    }
}
#pragma warning restore
