//HintName: IReturnNullableReferenceType.g.cs
// <auto-generated />
#nullable enable
#pragma warning disable
namespace Fluentish.Injectable.PropertyReturnTypeTests
{
    /// <inheritdoc cref="global::PropertyReturnTypeTests.ReturnNullableReferenceType"/>
    public interface IReturnNullableReferenceType
    {
        /// <inheritdoc cref="global::PropertyReturnTypeTests.ReturnNullableReferenceType.Test"/>
        global::PropertyReturnTypeTests.Example? Test { get; set; }

    }
}
#pragma warning restore
