//HintName: Array.g.cs
// <auto-generated />
#pragma warning disable
namespace Fluentish.Injectable.MethodReturnTests
{
    /// <inheritdoc cref="global::MethodReturnTests.Array"/>
    [global::System.Diagnostics.DebuggerStepThrough]
    public class ArrayService : IArray
    {
        /// <inheritdoc cref="global::MethodReturnTests.Array.Test"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public global::MethodReturnTests.Example[] Test()
            => global::MethodReturnTests.Array.Test();

    }
}
#pragma warning restore
