//HintName: IFile.g.cs
// <auto-generated />
#nullable enable
#pragma warning disable
namespace Fluentish.Injectable.System.IO
{
    /// <inheritdoc cref="global::System.IO.File"/>
    public interface IFile
    {
        /// <inheritdoc cref="global::System.IO.File.OpenText"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        global::System.IO.StreamReader OpenText(string path);

        /// <inheritdoc cref="global::System.IO.File.CreateText"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        global::System.IO.StreamWriter CreateText(string path);

        /// <inheritdoc cref="global::System.IO.File.AppendText"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        global::System.IO.StreamWriter AppendText(string path);

        /// <inheritdoc cref="global::System.IO.File.Copy"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        void Copy(string sourceFileName, string destFileName);

        /// <inheritdoc cref="global::System.IO.File.Copy"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        void Copy(string sourceFileName, string destFileName, bool overwrite);

        /// <inheritdoc cref="global::System.IO.File.Create"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        global::System.IO.FileStream Create(string path);

        /// <inheritdoc cref="global::System.IO.File.Create"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        global::System.IO.FileStream Create(string path, int bufferSize);

        /// <inheritdoc cref="global::System.IO.File.Create"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        global::System.IO.FileStream Create(string path, int bufferSize, global::System.IO.FileOptions options);

        /// <inheritdoc cref="global::System.IO.File.Delete"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        void Delete(string path);

        /// <inheritdoc cref="global::System.IO.File.Exists"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        bool Exists([global::System.Diagnostics.CodeAnalysis.NotNullWhenAttribute(true)] string? path);

        /// <inheritdoc cref="global::System.IO.File.Open"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        global::System.IO.FileStream Open(string path, global::System.IO.FileStreamOptions options);

        /// <inheritdoc cref="global::System.IO.File.Open"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        global::System.IO.FileStream Open(string path, global::System.IO.FileMode mode);

        /// <inheritdoc cref="global::System.IO.File.Open"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        global::System.IO.FileStream Open(string path, global::System.IO.FileMode mode, global::System.IO.FileAccess access);

        /// <inheritdoc cref="global::System.IO.File.Open"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        global::System.IO.FileStream Open(string path, global::System.IO.FileMode mode, global::System.IO.FileAccess access, global::System.IO.FileShare share);

        /// <inheritdoc cref="global::System.IO.File.OpenHandle"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        global::Microsoft.Win32.SafeHandles.SafeFileHandle OpenHandle(string path, global::System.IO.FileMode mode, global::System.IO.FileAccess access, global::System.IO.FileShare share, global::System.IO.FileOptions options, long preallocationSize);

        /// <inheritdoc cref="global::System.IO.File.SetCreationTime"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        void SetCreationTime(string path, global::System.DateTime creationTime);

        /// <inheritdoc cref="global::System.IO.File.SetCreationTime"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        void SetCreationTime(global::Microsoft.Win32.SafeHandles.SafeFileHandle fileHandle, global::System.DateTime creationTime);

        /// <inheritdoc cref="global::System.IO.File.SetCreationTimeUtc"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        void SetCreationTimeUtc(string path, global::System.DateTime creationTimeUtc);

        /// <inheritdoc cref="global::System.IO.File.SetCreationTimeUtc"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        void SetCreationTimeUtc(global::Microsoft.Win32.SafeHandles.SafeFileHandle fileHandle, global::System.DateTime creationTimeUtc);

        /// <inheritdoc cref="global::System.IO.File.GetCreationTime"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        global::System.DateTime GetCreationTime(string path);

        /// <inheritdoc cref="global::System.IO.File.GetCreationTime"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        global::System.DateTime GetCreationTime(global::Microsoft.Win32.SafeHandles.SafeFileHandle fileHandle);

        /// <inheritdoc cref="global::System.IO.File.GetCreationTimeUtc"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        global::System.DateTime GetCreationTimeUtc(string path);

        /// <inheritdoc cref="global::System.IO.File.GetCreationTimeUtc"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        global::System.DateTime GetCreationTimeUtc(global::Microsoft.Win32.SafeHandles.SafeFileHandle fileHandle);

        /// <inheritdoc cref="global::System.IO.File.SetLastAccessTime"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        void SetLastAccessTime(string path, global::System.DateTime lastAccessTime);

        /// <inheritdoc cref="global::System.IO.File.SetLastAccessTime"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        void SetLastAccessTime(global::Microsoft.Win32.SafeHandles.SafeFileHandle fileHandle, global::System.DateTime lastAccessTime);

        /// <inheritdoc cref="global::System.IO.File.SetLastAccessTimeUtc"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        void SetLastAccessTimeUtc(string path, global::System.DateTime lastAccessTimeUtc);

        /// <inheritdoc cref="global::System.IO.File.SetLastAccessTimeUtc"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        void SetLastAccessTimeUtc(global::Microsoft.Win32.SafeHandles.SafeFileHandle fileHandle, global::System.DateTime lastAccessTimeUtc);

        /// <inheritdoc cref="global::System.IO.File.GetLastAccessTime"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        global::System.DateTime GetLastAccessTime(string path);

        /// <inheritdoc cref="global::System.IO.File.GetLastAccessTime"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        global::System.DateTime GetLastAccessTime(global::Microsoft.Win32.SafeHandles.SafeFileHandle fileHandle);

        /// <inheritdoc cref="global::System.IO.File.GetLastAccessTimeUtc"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        global::System.DateTime GetLastAccessTimeUtc(string path);

        /// <inheritdoc cref="global::System.IO.File.GetLastAccessTimeUtc"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        global::System.DateTime GetLastAccessTimeUtc(global::Microsoft.Win32.SafeHandles.SafeFileHandle fileHandle);

        /// <inheritdoc cref="global::System.IO.File.SetLastWriteTime"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        void SetLastWriteTime(string path, global::System.DateTime lastWriteTime);

        /// <inheritdoc cref="global::System.IO.File.SetLastWriteTime"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        void SetLastWriteTime(global::Microsoft.Win32.SafeHandles.SafeFileHandle fileHandle, global::System.DateTime lastWriteTime);

        /// <inheritdoc cref="global::System.IO.File.SetLastWriteTimeUtc"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        void SetLastWriteTimeUtc(string path, global::System.DateTime lastWriteTimeUtc);

        /// <inheritdoc cref="global::System.IO.File.SetLastWriteTimeUtc"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        void SetLastWriteTimeUtc(global::Microsoft.Win32.SafeHandles.SafeFileHandle fileHandle, global::System.DateTime lastWriteTimeUtc);

        /// <inheritdoc cref="global::System.IO.File.GetLastWriteTime"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        global::System.DateTime GetLastWriteTime(string path);

        /// <inheritdoc cref="global::System.IO.File.GetLastWriteTime"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        global::System.DateTime GetLastWriteTime(global::Microsoft.Win32.SafeHandles.SafeFileHandle fileHandle);

        /// <inheritdoc cref="global::System.IO.File.GetLastWriteTimeUtc"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        global::System.DateTime GetLastWriteTimeUtc(string path);

        /// <inheritdoc cref="global::System.IO.File.GetLastWriteTimeUtc"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        global::System.DateTime GetLastWriteTimeUtc(global::Microsoft.Win32.SafeHandles.SafeFileHandle fileHandle);

        /// <inheritdoc cref="global::System.IO.File.GetAttributes"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        global::System.IO.FileAttributes GetAttributes(string path);

        /// <inheritdoc cref="global::System.IO.File.GetAttributes"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        global::System.IO.FileAttributes GetAttributes(global::Microsoft.Win32.SafeHandles.SafeFileHandle fileHandle);

        /// <inheritdoc cref="global::System.IO.File.SetAttributes"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        void SetAttributes(string path, global::System.IO.FileAttributes fileAttributes);

        /// <inheritdoc cref="global::System.IO.File.SetAttributes"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        void SetAttributes(global::Microsoft.Win32.SafeHandles.SafeFileHandle fileHandle, global::System.IO.FileAttributes fileAttributes);

        /// <inheritdoc cref="global::System.IO.File.GetUnixFileMode"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        [global::System.Runtime.Versioning.UnsupportedOSPlatformAttribute("windows")]
        global::System.IO.UnixFileMode GetUnixFileMode(string path);

        /// <inheritdoc cref="global::System.IO.File.GetUnixFileMode"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        [global::System.Runtime.Versioning.UnsupportedOSPlatformAttribute("windows")]
        global::System.IO.UnixFileMode GetUnixFileMode(global::Microsoft.Win32.SafeHandles.SafeFileHandle fileHandle);

        /// <inheritdoc cref="global::System.IO.File.SetUnixFileMode"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        [global::System.Runtime.Versioning.UnsupportedOSPlatformAttribute("windows")]
        void SetUnixFileMode(string path, global::System.IO.UnixFileMode mode);

        /// <inheritdoc cref="global::System.IO.File.SetUnixFileMode"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        [global::System.Runtime.Versioning.UnsupportedOSPlatformAttribute("windows")]
        void SetUnixFileMode(global::Microsoft.Win32.SafeHandles.SafeFileHandle fileHandle, global::System.IO.UnixFileMode mode);

        /// <inheritdoc cref="global::System.IO.File.OpenRead"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        global::System.IO.FileStream OpenRead(string path);

        /// <inheritdoc cref="global::System.IO.File.OpenWrite"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        global::System.IO.FileStream OpenWrite(string path);

        /// <inheritdoc cref="global::System.IO.File.ReadAllText"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        string ReadAllText(string path);

        /// <inheritdoc cref="global::System.IO.File.ReadAllText"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        string ReadAllText(string path, global::System.Text.Encoding encoding);

        /// <inheritdoc cref="global::System.IO.File.WriteAllText"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        void WriteAllText(string path, string? contents);

        /// <inheritdoc cref="global::System.IO.File.WriteAllText"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        void WriteAllText(string path, string? contents, global::System.Text.Encoding encoding);

        /// <inheritdoc cref="global::System.IO.File.ReadAllBytes"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        byte[] ReadAllBytes(string path);

        /// <inheritdoc cref="global::System.IO.File.WriteAllBytes"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        void WriteAllBytes(string path, byte[] bytes);

        /// <inheritdoc cref="global::System.IO.File.ReadAllLines"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        string[] ReadAllLines(string path);

        /// <inheritdoc cref="global::System.IO.File.ReadAllLines"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        string[] ReadAllLines(string path, global::System.Text.Encoding encoding);

        /// <inheritdoc cref="global::System.IO.File.ReadLines"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        global::System.Collections.Generic.IEnumerable<string> ReadLines(string path);

        /// <inheritdoc cref="global::System.IO.File.ReadLines"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        global::System.Collections.Generic.IEnumerable<string> ReadLines(string path, global::System.Text.Encoding encoding);

        /// <inheritdoc cref="global::System.IO.File.ReadLinesAsync"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        global::System.Collections.Generic.IAsyncEnumerable<string> ReadLinesAsync(string path, global::System.Threading.CancellationToken cancellationToken);

        /// <inheritdoc cref="global::System.IO.File.ReadLinesAsync"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        global::System.Collections.Generic.IAsyncEnumerable<string> ReadLinesAsync(string path, global::System.Text.Encoding encoding, global::System.Threading.CancellationToken cancellationToken);

        /// <inheritdoc cref="global::System.IO.File.WriteAllLines"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        void WriteAllLines(string path, string[] contents);

        /// <inheritdoc cref="global::System.IO.File.WriteAllLines"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        void WriteAllLines(string path, global::System.Collections.Generic.IEnumerable<string> contents);

        /// <inheritdoc cref="global::System.IO.File.WriteAllLines"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        void WriteAllLines(string path, string[] contents, global::System.Text.Encoding encoding);

        /// <inheritdoc cref="global::System.IO.File.WriteAllLines"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        void WriteAllLines(string path, global::System.Collections.Generic.IEnumerable<string> contents, global::System.Text.Encoding encoding);

        /// <inheritdoc cref="global::System.IO.File.AppendAllText"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        void AppendAllText(string path, string? contents);

        /// <inheritdoc cref="global::System.IO.File.AppendAllText"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        void AppendAllText(string path, string? contents, global::System.Text.Encoding encoding);

        /// <inheritdoc cref="global::System.IO.File.AppendAllLines"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        void AppendAllLines(string path, global::System.Collections.Generic.IEnumerable<string> contents);

        /// <inheritdoc cref="global::System.IO.File.AppendAllLines"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        void AppendAllLines(string path, global::System.Collections.Generic.IEnumerable<string> contents, global::System.Text.Encoding encoding);

        /// <inheritdoc cref="global::System.IO.File.Replace"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        void Replace(string sourceFileName, string destinationFileName, string? destinationBackupFileName);

        /// <inheritdoc cref="global::System.IO.File.Replace"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        void Replace(string sourceFileName, string destinationFileName, string? destinationBackupFileName, bool ignoreMetadataErrors);

        /// <inheritdoc cref="global::System.IO.File.Move"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        void Move(string sourceFileName, string destFileName);

        /// <inheritdoc cref="global::System.IO.File.Move"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        void Move(string sourceFileName, string destFileName, bool overwrite);

        /// <inheritdoc cref="global::System.IO.File.Encrypt"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        [global::System.Runtime.Versioning.SupportedOSPlatformAttribute("windows")]
        void Encrypt(string path);

        /// <inheritdoc cref="global::System.IO.File.Decrypt"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        [global::System.Runtime.Versioning.SupportedOSPlatformAttribute("windows")]
        void Decrypt(string path);

        /// <inheritdoc cref="global::System.IO.File.ReadAllTextAsync"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        global::System.Threading.Tasks.Task<string> ReadAllTextAsync(string path, global::System.Threading.CancellationToken cancellationToken);

        /// <inheritdoc cref="global::System.IO.File.ReadAllTextAsync"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        global::System.Threading.Tasks.Task<string> ReadAllTextAsync(string path, global::System.Text.Encoding encoding, global::System.Threading.CancellationToken cancellationToken);

        /// <inheritdoc cref="global::System.IO.File.WriteAllTextAsync"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        global::System.Threading.Tasks.Task WriteAllTextAsync(string path, string? contents, global::System.Threading.CancellationToken cancellationToken);

        /// <inheritdoc cref="global::System.IO.File.WriteAllTextAsync"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        global::System.Threading.Tasks.Task WriteAllTextAsync(string path, string? contents, global::System.Text.Encoding encoding, global::System.Threading.CancellationToken cancellationToken);

        /// <inheritdoc cref="global::System.IO.File.ReadAllBytesAsync"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        global::System.Threading.Tasks.Task<byte[]> ReadAllBytesAsync(string path, global::System.Threading.CancellationToken cancellationToken);

        /// <inheritdoc cref="global::System.IO.File.WriteAllBytesAsync"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        global::System.Threading.Tasks.Task WriteAllBytesAsync(string path, byte[] bytes, global::System.Threading.CancellationToken cancellationToken);

        /// <inheritdoc cref="global::System.IO.File.ReadAllLinesAsync"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        global::System.Threading.Tasks.Task<string[]> ReadAllLinesAsync(string path, global::System.Threading.CancellationToken cancellationToken);

        /// <inheritdoc cref="global::System.IO.File.ReadAllLinesAsync"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        global::System.Threading.Tasks.Task<string[]> ReadAllLinesAsync(string path, global::System.Text.Encoding encoding, global::System.Threading.CancellationToken cancellationToken);

        /// <inheritdoc cref="global::System.IO.File.WriteAllLinesAsync"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        global::System.Threading.Tasks.Task WriteAllLinesAsync(string path, global::System.Collections.Generic.IEnumerable<string> contents, global::System.Threading.CancellationToken cancellationToken);

        /// <inheritdoc cref="global::System.IO.File.WriteAllLinesAsync"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        global::System.Threading.Tasks.Task WriteAllLinesAsync(string path, global::System.Collections.Generic.IEnumerable<string> contents, global::System.Text.Encoding encoding, global::System.Threading.CancellationToken cancellationToken);

        /// <inheritdoc cref="global::System.IO.File.AppendAllTextAsync"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        global::System.Threading.Tasks.Task AppendAllTextAsync(string path, string? contents, global::System.Threading.CancellationToken cancellationToken);

        /// <inheritdoc cref="global::System.IO.File.AppendAllTextAsync"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        global::System.Threading.Tasks.Task AppendAllTextAsync(string path, string? contents, global::System.Text.Encoding encoding, global::System.Threading.CancellationToken cancellationToken);

        /// <inheritdoc cref="global::System.IO.File.AppendAllLinesAsync"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        global::System.Threading.Tasks.Task AppendAllLinesAsync(string path, global::System.Collections.Generic.IEnumerable<string> contents, global::System.Threading.CancellationToken cancellationToken);

        /// <inheritdoc cref="global::System.IO.File.AppendAllLinesAsync"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        global::System.Threading.Tasks.Task AppendAllLinesAsync(string path, global::System.Collections.Generic.IEnumerable<string> contents, global::System.Text.Encoding encoding, global::System.Threading.CancellationToken cancellationToken);

        /// <inheritdoc cref="global::System.IO.File.CreateSymbolicLink"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        global::System.IO.FileSystemInfo CreateSymbolicLink(string path, string pathToTarget);

        /// <inheritdoc cref="global::System.IO.File.ResolveLinkTarget"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        global::System.IO.FileSystemInfo? ResolveLinkTarget(string linkPath, bool returnFinalTarget);

    }
}
#pragma warning restore
