//HintName: IDateTime.g.cs
// <auto-generated />
#nullable enable
#pragma warning disable
namespace Fluentish.Injectable.System
{
    /// <inheritdoc cref="global::System.DateTime"/>
    public interface IDateTime
    {
        /// <inheritdoc cref="global::System.DateTime.MinValue"/>
        global::System.DateTime MinValue { get; }

        /// <inheritdoc cref="global::System.DateTime.MaxValue"/>
        global::System.DateTime MaxValue { get; }

        /// <inheritdoc cref="global::System.DateTime.UnixEpoch"/>
        global::System.DateTime UnixEpoch { get; }

        /// <inheritdoc cref="global::System.DateTime.Compare"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        int Compare(global::System.DateTime t1, global::System.DateTime t2);

        /// <inheritdoc cref="global::System.DateTime.DaysInMonth"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        int DaysInMonth(int year, int month);

        /// <inheritdoc cref="global::System.DateTime.Equals"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        bool Equals(global::System.DateTime t1, global::System.DateTime t2);

        /// <inheritdoc cref="global::System.DateTime.FromBinary"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        global::System.DateTime FromBinary(long dateData);

        /// <inheritdoc cref="global::System.DateTime.FromFileTime"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        global::System.DateTime FromFileTime(long fileTime);

        /// <inheritdoc cref="global::System.DateTime.FromFileTimeUtc"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        global::System.DateTime FromFileTimeUtc(long fileTime);

        /// <inheritdoc cref="global::System.DateTime.FromOADate"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        global::System.DateTime FromOADate(double d);

        /// <inheritdoc cref="global::System.DateTime.SpecifyKind"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        global::System.DateTime SpecifyKind(global::System.DateTime value, global::System.DateTimeKind kind);

        /// <inheritdoc cref="global::System.DateTime.IsLeapYear"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        bool IsLeapYear(int year);

        /// <inheritdoc cref="global::System.DateTime.Parse"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        global::System.DateTime Parse(string s);

        /// <inheritdoc cref="global::System.DateTime.Parse"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        global::System.DateTime Parse(string s, global::System.IFormatProvider? provider);

        /// <inheritdoc cref="global::System.DateTime.Parse"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        global::System.DateTime Parse(string s, global::System.IFormatProvider? provider, global::System.Globalization.DateTimeStyles styles);

        /// <inheritdoc cref="global::System.DateTime.Parse"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        global::System.DateTime Parse(global::System.ReadOnlySpan<char> s, global::System.IFormatProvider? provider, global::System.Globalization.DateTimeStyles styles);

        /// <inheritdoc cref="global::System.DateTime.ParseExact"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        global::System.DateTime ParseExact(string s, [global::System.Diagnostics.CodeAnalysis.StringSyntaxAttribute("DateTimeFormat")] string format, global::System.IFormatProvider? provider);

        /// <inheritdoc cref="global::System.DateTime.ParseExact"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        global::System.DateTime ParseExact(string s, [global::System.Diagnostics.CodeAnalysis.StringSyntaxAttribute("DateTimeFormat")] string format, global::System.IFormatProvider? provider, global::System.Globalization.DateTimeStyles style);

        /// <inheritdoc cref="global::System.DateTime.ParseExact"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        global::System.DateTime ParseExact(global::System.ReadOnlySpan<char> s, [global::System.Diagnostics.CodeAnalysis.StringSyntaxAttribute("DateTimeFormat")] global::System.ReadOnlySpan<char> format, global::System.IFormatProvider? provider, global::System.Globalization.DateTimeStyles style);

        /// <inheritdoc cref="global::System.DateTime.ParseExact"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        global::System.DateTime ParseExact(string s, [global::System.Diagnostics.CodeAnalysis.StringSyntaxAttribute("DateTimeFormat")] string[] formats, global::System.IFormatProvider? provider, global::System.Globalization.DateTimeStyles style);

        /// <inheritdoc cref="global::System.DateTime.ParseExact"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        global::System.DateTime ParseExact(global::System.ReadOnlySpan<char> s, [global::System.Diagnostics.CodeAnalysis.StringSyntaxAttribute("DateTimeFormat")] string[] formats, global::System.IFormatProvider? provider, global::System.Globalization.DateTimeStyles style);

        /// <inheritdoc cref="global::System.DateTime.TryParse"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        bool TryParse([global::System.Diagnostics.CodeAnalysis.NotNullWhenAttribute(true)] string? s, out global::System.DateTime result);

        /// <inheritdoc cref="global::System.DateTime.TryParse"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        bool TryParse(global::System.ReadOnlySpan<char> s, out global::System.DateTime result);

        /// <inheritdoc cref="global::System.DateTime.TryParse"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        bool TryParse([global::System.Diagnostics.CodeAnalysis.NotNullWhenAttribute(true)] string? s, global::System.IFormatProvider? provider, global::System.Globalization.DateTimeStyles styles, out global::System.DateTime result);

        /// <inheritdoc cref="global::System.DateTime.TryParse"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        bool TryParse(global::System.ReadOnlySpan<char> s, global::System.IFormatProvider? provider, global::System.Globalization.DateTimeStyles styles, out global::System.DateTime result);

        /// <inheritdoc cref="global::System.DateTime.TryParseExact"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        bool TryParseExact([global::System.Diagnostics.CodeAnalysis.NotNullWhenAttribute(true)] string? s, [global::System.Diagnostics.CodeAnalysis.NotNullWhenAttribute(true), global::System.Diagnostics.CodeAnalysis.StringSyntaxAttribute("DateTimeFormat")] string? format, global::System.IFormatProvider? provider, global::System.Globalization.DateTimeStyles style, out global::System.DateTime result);

        /// <inheritdoc cref="global::System.DateTime.TryParseExact"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        bool TryParseExact(global::System.ReadOnlySpan<char> s, [global::System.Diagnostics.CodeAnalysis.StringSyntaxAttribute("DateTimeFormat")] global::System.ReadOnlySpan<char> format, global::System.IFormatProvider? provider, global::System.Globalization.DateTimeStyles style, out global::System.DateTime result);

        /// <inheritdoc cref="global::System.DateTime.TryParseExact"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        bool TryParseExact([global::System.Diagnostics.CodeAnalysis.NotNullWhenAttribute(true)] string? s, [global::System.Diagnostics.CodeAnalysis.NotNullWhenAttribute(true), global::System.Diagnostics.CodeAnalysis.StringSyntaxAttribute("DateTimeFormat")] string?[] formats, global::System.IFormatProvider? provider, global::System.Globalization.DateTimeStyles style, out global::System.DateTime result);

        /// <inheritdoc cref="global::System.DateTime.TryParseExact"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        bool TryParseExact(global::System.ReadOnlySpan<char> s, [global::System.Diagnostics.CodeAnalysis.NotNullWhenAttribute(true), global::System.Diagnostics.CodeAnalysis.StringSyntaxAttribute("DateTimeFormat")] string?[] formats, global::System.IFormatProvider? provider, global::System.Globalization.DateTimeStyles style, out global::System.DateTime result);

        /// <inheritdoc cref="global::System.DateTime.TryParse"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        bool TryParse([global::System.Diagnostics.CodeAnalysis.NotNullWhenAttribute(true)] string? s, global::System.IFormatProvider? provider, out global::System.DateTime result);

        /// <inheritdoc cref="global::System.DateTime.Parse"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        global::System.DateTime Parse(global::System.ReadOnlySpan<char> s, global::System.IFormatProvider? provider);

        /// <inheritdoc cref="global::System.DateTime.TryParse"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        bool TryParse(global::System.ReadOnlySpan<char> s, global::System.IFormatProvider? provider, out global::System.DateTime result);

        /// <inheritdoc cref="global::System.DateTime.Now"/>
        global::System.DateTime Now { get; }

        /// <inheritdoc cref="global::System.DateTime.Today"/>
        global::System.DateTime Today { get; }

        /// <inheritdoc cref="global::System.DateTime.UtcNow"/>
        global::System.DateTime UtcNow { get; }

    }
}
#pragma warning restore
