//HintName: InternalProperty.g.cs
// <auto-generated />
#pragma warning disable
namespace Fluentish.Injectable.PropertyAccessibilityTests
{
    /// <inheritdoc cref="global::PropertyAccessibilityTests.InternalProperty"/>
    [global::System.Diagnostics.DebuggerStepThrough]
    public class InternalPropertyService : IInternalProperty
    {
    }
}
#pragma warning restore
