//HintName: IInternalProperty.g.cs
// <auto-generated />
#pragma warning disable
namespace Fluentish.Injectable.PropertyAccessibilityTests
{
    /// <inheritdoc cref="global::PropertyAccessibilityTests.InternalProperty"/>
    public interface IInternalProperty
    {
    }
}
#pragma warning restore
