//HintName: IReturnSugarTuple.g.cs
// <auto-generated />
#pragma warning disable
namespace Fluentish.Injectable.ConstReturnTypeTests
{
    /// <inheritdoc cref="global::ConstReturnTypeTests.ReturnSugarTuple"/>
    public interface IReturnSugarTuple
    {
        /// <inheritdoc cref="global::ConstReturnTypeTests.ReturnSugarTuple.Test"/>
        (string left, object right) Test { get; }

    }
}
#pragma warning restore
