//HintName: IBitConverter.g.cs
// <auto-generated />
#pragma warning disable
namespace Fluentish.Injectable.System
{
    /// <inheritdoc cref="global::System.BitConverter"/>
    public interface IBitConverter
    {
        /// <inheritdoc cref="global::System.BitConverter.IsLittleEndian"/>
        bool IsLittleEndian { get; }

        /// <inheritdoc cref="global::System.BitConverter.GetBytes"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        byte[] GetBytes(bool value);

        /// <inheritdoc cref="global::System.BitConverter.TryWriteBytes"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        bool TryWriteBytes(global::System.Span<byte> destination, bool value);

        /// <inheritdoc cref="global::System.BitConverter.GetBytes"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        byte[] GetBytes(char value);

        /// <inheritdoc cref="global::System.BitConverter.TryWriteBytes"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        bool TryWriteBytes(global::System.Span<byte> destination, char value);

        /// <inheritdoc cref="global::System.BitConverter.GetBytes"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        byte[] GetBytes(short value);

        /// <inheritdoc cref="global::System.BitConverter.TryWriteBytes"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        bool TryWriteBytes(global::System.Span<byte> destination, short value);

        /// <inheritdoc cref="global::System.BitConverter.GetBytes"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        byte[] GetBytes(int value);

        /// <inheritdoc cref="global::System.BitConverter.TryWriteBytes"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        bool TryWriteBytes(global::System.Span<byte> destination, int value);

        /// <inheritdoc cref="global::System.BitConverter.GetBytes"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        byte[] GetBytes(long value);

        /// <inheritdoc cref="global::System.BitConverter.TryWriteBytes"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        bool TryWriteBytes(global::System.Span<byte> destination, long value);

        /// <inheritdoc cref="global::System.BitConverter.GetBytes"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        [global::System.CLSCompliantAttribute(false)]
        byte[] GetBytes(ushort value);

        /// <inheritdoc cref="global::System.BitConverter.TryWriteBytes"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        [global::System.CLSCompliantAttribute(false)]
        bool TryWriteBytes(global::System.Span<byte> destination, ushort value);

        /// <inheritdoc cref="global::System.BitConverter.GetBytes"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        [global::System.CLSCompliantAttribute(false)]
        byte[] GetBytes(uint value);

        /// <inheritdoc cref="global::System.BitConverter.TryWriteBytes"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        [global::System.CLSCompliantAttribute(false)]
        bool TryWriteBytes(global::System.Span<byte> destination, uint value);

        /// <inheritdoc cref="global::System.BitConverter.GetBytes"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        [global::System.CLSCompliantAttribute(false)]
        byte[] GetBytes(ulong value);

        /// <inheritdoc cref="global::System.BitConverter.TryWriteBytes"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        [global::System.CLSCompliantAttribute(false)]
        bool TryWriteBytes(global::System.Span<byte> destination, ulong value);

        /// <inheritdoc cref="global::System.BitConverter.GetBytes"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        byte[] GetBytes(global::System.Half value);

        /// <inheritdoc cref="global::System.BitConverter.TryWriteBytes"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        bool TryWriteBytes(global::System.Span<byte> destination, global::System.Half value);

        /// <inheritdoc cref="global::System.BitConverter.GetBytes"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        byte[] GetBytes(float value);

        /// <inheritdoc cref="global::System.BitConverter.TryWriteBytes"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        bool TryWriteBytes(global::System.Span<byte> destination, float value);

        /// <inheritdoc cref="global::System.BitConverter.GetBytes"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        byte[] GetBytes(double value);

        /// <inheritdoc cref="global::System.BitConverter.TryWriteBytes"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        bool TryWriteBytes(global::System.Span<byte> destination, double value);

        /// <inheritdoc cref="global::System.BitConverter.ToChar"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        char ToChar(byte[] value, int startIndex);

        /// <inheritdoc cref="global::System.BitConverter.ToChar"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        char ToChar(global::System.ReadOnlySpan<byte> value);

        /// <inheritdoc cref="global::System.BitConverter.ToInt16"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        short ToInt16(byte[] value, int startIndex);

        /// <inheritdoc cref="global::System.BitConverter.ToInt16"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        short ToInt16(global::System.ReadOnlySpan<byte> value);

        /// <inheritdoc cref="global::System.BitConverter.ToInt32"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        int ToInt32(byte[] value, int startIndex);

        /// <inheritdoc cref="global::System.BitConverter.ToInt32"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        int ToInt32(global::System.ReadOnlySpan<byte> value);

        /// <inheritdoc cref="global::System.BitConverter.ToInt64"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        long ToInt64(byte[] value, int startIndex);

        /// <inheritdoc cref="global::System.BitConverter.ToInt64"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        long ToInt64(global::System.ReadOnlySpan<byte> value);

        /// <inheritdoc cref="global::System.BitConverter.ToUInt16"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        [global::System.CLSCompliantAttribute(false)]
        ushort ToUInt16(byte[] value, int startIndex);

        /// <inheritdoc cref="global::System.BitConverter.ToUInt16"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        [global::System.CLSCompliantAttribute(false)]
        ushort ToUInt16(global::System.ReadOnlySpan<byte> value);

        /// <inheritdoc cref="global::System.BitConverter.ToUInt32"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        [global::System.CLSCompliantAttribute(false)]
        uint ToUInt32(byte[] value, int startIndex);

        /// <inheritdoc cref="global::System.BitConverter.ToUInt32"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        [global::System.CLSCompliantAttribute(false)]
        uint ToUInt32(global::System.ReadOnlySpan<byte> value);

        /// <inheritdoc cref="global::System.BitConverter.ToUInt64"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        [global::System.CLSCompliantAttribute(false)]
        ulong ToUInt64(byte[] value, int startIndex);

        /// <inheritdoc cref="global::System.BitConverter.ToUInt64"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        [global::System.CLSCompliantAttribute(false)]
        ulong ToUInt64(global::System.ReadOnlySpan<byte> value);

        /// <inheritdoc cref="global::System.BitConverter.ToHalf"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        global::System.Half ToHalf(byte[] value, int startIndex);

        /// <inheritdoc cref="global::System.BitConverter.ToHalf"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        global::System.Half ToHalf(global::System.ReadOnlySpan<byte> value);

        /// <inheritdoc cref="global::System.BitConverter.ToSingle"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        float ToSingle(byte[] value, int startIndex);

        /// <inheritdoc cref="global::System.BitConverter.ToSingle"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        float ToSingle(global::System.ReadOnlySpan<byte> value);

        /// <inheritdoc cref="global::System.BitConverter.ToDouble"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        double ToDouble(byte[] value, int startIndex);

        /// <inheritdoc cref="global::System.BitConverter.ToDouble"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        double ToDouble(global::System.ReadOnlySpan<byte> value);

        /// <inheritdoc cref="global::System.BitConverter.ToString"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        string ToString(byte[] value, int startIndex, int length);

        /// <inheritdoc cref="global::System.BitConverter.ToString"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        string ToString(byte[] value);

        /// <inheritdoc cref="global::System.BitConverter.ToString"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        string ToString(byte[] value, int startIndex);

        /// <inheritdoc cref="global::System.BitConverter.ToBoolean"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        bool ToBoolean(byte[] value, int startIndex);

        /// <inheritdoc cref="global::System.BitConverter.ToBoolean"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        bool ToBoolean(global::System.ReadOnlySpan<byte> value);

        /// <inheritdoc cref="global::System.BitConverter.DoubleToInt64Bits"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        long DoubleToInt64Bits(double value);

        /// <inheritdoc cref="global::System.BitConverter.Int64BitsToDouble"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        double Int64BitsToDouble(long value);

        /// <inheritdoc cref="global::System.BitConverter.SingleToInt32Bits"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        int SingleToInt32Bits(float value);

        /// <inheritdoc cref="global::System.BitConverter.Int32BitsToSingle"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        float Int32BitsToSingle(int value);

        /// <inheritdoc cref="global::System.BitConverter.HalfToInt16Bits"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        short HalfToInt16Bits(global::System.Half value);

        /// <inheritdoc cref="global::System.BitConverter.Int16BitsToHalf"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        global::System.Half Int16BitsToHalf(short value);

        /// <inheritdoc cref="global::System.BitConverter.DoubleToUInt64Bits"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        [global::System.CLSCompliantAttribute(false)]
        ulong DoubleToUInt64Bits(double value);

        /// <inheritdoc cref="global::System.BitConverter.UInt64BitsToDouble"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        [global::System.CLSCompliantAttribute(false)]
        double UInt64BitsToDouble(ulong value);

        /// <inheritdoc cref="global::System.BitConverter.SingleToUInt32Bits"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        [global::System.CLSCompliantAttribute(false)]
        uint SingleToUInt32Bits(float value);

        /// <inheritdoc cref="global::System.BitConverter.UInt32BitsToSingle"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        [global::System.CLSCompliantAttribute(false)]
        float UInt32BitsToSingle(uint value);

        /// <inheritdoc cref="global::System.BitConverter.HalfToUInt16Bits"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        [global::System.CLSCompliantAttribute(false)]
        ushort HalfToUInt16Bits(global::System.Half value);

        /// <inheritdoc cref="global::System.BitConverter.UInt16BitsToHalf"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        [global::System.CLSCompliantAttribute(false)]
        global::System.Half UInt16BitsToHalf(ushort value);
    }
}
#pragma warning restore
