//HintName: INetworkChange.g.cs
// <auto-generated />
#nullable enable
#pragma warning disable
namespace Fluentish.Injectable.System.Net.NetworkInformation
{
    /// <inheritdoc cref="global::System.Net.NetworkInformation.NetworkChange"/>
    public interface INetworkChange
    {
        /// <inheritdoc cref="global::System.Net.NetworkInformation.NetworkChange.RegisterNetworkChange"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never), global::System.ObsoleteAttribute("This API supports the .NET Framework infrastructure and is not intended to be used directly from your code.", true)]
        void RegisterNetworkChange(global::System.Net.NetworkInformation.NetworkChange nc);

        /// <inheritdoc cref="global::System.Net.NetworkInformation.NetworkChange.NetworkAvailabilityChanged"/>
        [global::System.Runtime.Versioning.UnsupportedOSPlatformAttribute("illumos"), global::System.Runtime.Versioning.UnsupportedOSPlatformAttribute("solaris")]
        event global::System.Net.NetworkInformation.NetworkAvailabilityChangedEventHandler? NetworkAvailabilityChanged;

        /// <inheritdoc cref="global::System.Net.NetworkInformation.NetworkChange.NetworkAddressChanged"/>
        [global::System.Runtime.Versioning.UnsupportedOSPlatformAttribute("illumos"), global::System.Runtime.Versioning.UnsupportedOSPlatformAttribute("solaris")]
        event global::System.Net.NetworkInformation.NetworkAddressChangedEventHandler? NetworkAddressChanged;

    }
}
#pragma warning restore
