//HintName: ReturnReferenceType.g.cs
// <auto-generated />
#pragma warning disable
namespace Fluentish.Injectable.PropertyReturnTypeTests
{
    /// <inheritdoc cref="global::PropertyReturnTypeTests.ReturnReferenceType"/>
    [global::System.Diagnostics.DebuggerStepThrough]
    public class ReturnReferenceTypeService: IReturnReferenceType
    {
        /// <inheritdoc cref="global::PropertyReturnTypeTests.ReturnReferenceType.Test"/>
        public global::PropertyReturnTypeTests.Example Test
        {
            get => global::PropertyReturnTypeTests.ReturnReferenceType.Test;
            set => global::PropertyReturnTypeTests.ReturnReferenceType.Test = value;
        }

    }
}
#pragma warning restore
