//HintName: ReturnValueType.g.cs
// <auto-generated />
#pragma warning disable
namespace Fluentish.Injectable.PropertyReturnTypeTests
{
    /// <inheritdoc cref="global::PropertyReturnTypeTests.ReturnValueType"/>
    [global::System.Diagnostics.DebuggerStepThrough]
    public class ReturnValueTypeService: IReturnValueType
    {
        /// <inheritdoc cref="global::PropertyReturnTypeTests.ReturnValueType.Test"/>
        public global::PropertyReturnTypeTests.Example Test
        {
            get => global::PropertyReturnTypeTests.ReturnValueType.Test;
            set => global::PropertyReturnTypeTests.ReturnValueType.Test = value;
        }

    }
}
#pragma warning restore
