//HintName: NullableDateTime.g.cs
// <auto-generated />
#nullable enable
#pragma warning disable
namespace Fluentish.Injectable.MethodReturnTests
{
    /// <inheritdoc cref="global::MethodReturnTests.NullableDateTime"/>
    [global::System.Diagnostics.DebuggerStepThrough]
    public class NullableDateTimeService: INullableDateTime
    {
        /// <inheritdoc cref="global::MethodReturnTests.NullableDateTime.Test"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public global::System.Nullable<global::System.DateTime> Test() => global::MethodReturnTests.NullableDateTime.Test();
    }
}
#pragma warning restore
