//HintName: INullableDateTime.g.cs
// <auto-generated />
#nullable enable
#pragma warning disable
namespace Fluentish.Injectable.MethodReturnTests
{
    /// <inheritdoc cref="global::MethodReturnTests.NullableDateTime"/>
    public interface INullableDateTime
    {
        /// <inheritdoc cref="global::MethodReturnTests.NullableDateTime.Test"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        global::System.Nullable<global::System.DateTime> Test();
    }
}
#pragma warning restore
