//HintName: Empty.g.cs
// <auto-generated />
#pragma warning disable
namespace NamespacePrefixTests
{
    /// <inheritdoc cref="global::NamespacePrefixTests.Empty"/>
    [global::System.Diagnostics.DebuggerStepThrough]
    public class EmptyService : IEmpty
    {
        /// <inheritdoc cref="global::NamespacePrefixTests.Empty.Test"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public void Test()
             => global::NamespacePrefixTests.Empty.Test();
    }
}
#pragma warning restore
