//HintName: IDirectory.g.cs
// <auto-generated />
#nullable enable
#pragma warning disable
namespace Fluentish.Injectable.System.IO
{
    /// <inheritdoc cref="global::System.IO.Directory"/>
    public interface IDirectory
    {
        /// <inheritdoc cref="global::System.IO.Directory.GetParent"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        global::System.IO.DirectoryInfo? GetParent(string path);

        /// <inheritdoc cref="global::System.IO.Directory.CreateDirectory"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        global::System.IO.DirectoryInfo CreateDirectory(string path);

        /// <inheritdoc cref="global::System.IO.Directory.CreateDirectory"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        [global::System.Runtime.Versioning.UnsupportedOSPlatformAttribute("windows")]
        global::System.IO.DirectoryInfo CreateDirectory(string path, global::System.IO.UnixFileMode unixCreateMode);

        /// <inheritdoc cref="global::System.IO.Directory.CreateTempSubdirectory"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        global::System.IO.DirectoryInfo CreateTempSubdirectory(string? prefix);

        /// <inheritdoc cref="global::System.IO.Directory.Exists"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        bool Exists([global::System.Diagnostics.CodeAnalysis.NotNullWhenAttribute(true)] string? path);

        /// <inheritdoc cref="global::System.IO.Directory.SetCreationTime"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        void SetCreationTime(string path, global::System.DateTime creationTime);

        /// <inheritdoc cref="global::System.IO.Directory.SetCreationTimeUtc"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        void SetCreationTimeUtc(string path, global::System.DateTime creationTimeUtc);

        /// <inheritdoc cref="global::System.IO.Directory.GetCreationTime"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        global::System.DateTime GetCreationTime(string path);

        /// <inheritdoc cref="global::System.IO.Directory.GetCreationTimeUtc"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        global::System.DateTime GetCreationTimeUtc(string path);

        /// <inheritdoc cref="global::System.IO.Directory.SetLastWriteTime"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        void SetLastWriteTime(string path, global::System.DateTime lastWriteTime);

        /// <inheritdoc cref="global::System.IO.Directory.SetLastWriteTimeUtc"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        void SetLastWriteTimeUtc(string path, global::System.DateTime lastWriteTimeUtc);

        /// <inheritdoc cref="global::System.IO.Directory.GetLastWriteTime"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        global::System.DateTime GetLastWriteTime(string path);

        /// <inheritdoc cref="global::System.IO.Directory.GetLastWriteTimeUtc"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        global::System.DateTime GetLastWriteTimeUtc(string path);

        /// <inheritdoc cref="global::System.IO.Directory.SetLastAccessTime"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        void SetLastAccessTime(string path, global::System.DateTime lastAccessTime);

        /// <inheritdoc cref="global::System.IO.Directory.SetLastAccessTimeUtc"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        void SetLastAccessTimeUtc(string path, global::System.DateTime lastAccessTimeUtc);

        /// <inheritdoc cref="global::System.IO.Directory.GetLastAccessTime"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        global::System.DateTime GetLastAccessTime(string path);

        /// <inheritdoc cref="global::System.IO.Directory.GetLastAccessTimeUtc"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        global::System.DateTime GetLastAccessTimeUtc(string path);

        /// <inheritdoc cref="global::System.IO.Directory.GetFiles"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        string[] GetFiles(string path);

        /// <inheritdoc cref="global::System.IO.Directory.GetFiles"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        string[] GetFiles(string path, string searchPattern);

        /// <inheritdoc cref="global::System.IO.Directory.GetFiles"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        string[] GetFiles(string path, string searchPattern, global::System.IO.SearchOption searchOption);

        /// <inheritdoc cref="global::System.IO.Directory.GetFiles"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        string[] GetFiles(string path, string searchPattern, global::System.IO.EnumerationOptions enumerationOptions);

        /// <inheritdoc cref="global::System.IO.Directory.GetDirectories"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        string[] GetDirectories(string path);

        /// <inheritdoc cref="global::System.IO.Directory.GetDirectories"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        string[] GetDirectories(string path, string searchPattern);

        /// <inheritdoc cref="global::System.IO.Directory.GetDirectories"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        string[] GetDirectories(string path, string searchPattern, global::System.IO.SearchOption searchOption);

        /// <inheritdoc cref="global::System.IO.Directory.GetDirectories"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        string[] GetDirectories(string path, string searchPattern, global::System.IO.EnumerationOptions enumerationOptions);

        /// <inheritdoc cref="global::System.IO.Directory.GetFileSystemEntries"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        string[] GetFileSystemEntries(string path);

        /// <inheritdoc cref="global::System.IO.Directory.GetFileSystemEntries"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        string[] GetFileSystemEntries(string path, string searchPattern);

        /// <inheritdoc cref="global::System.IO.Directory.GetFileSystemEntries"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        string[] GetFileSystemEntries(string path, string searchPattern, global::System.IO.SearchOption searchOption);

        /// <inheritdoc cref="global::System.IO.Directory.GetFileSystemEntries"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        string[] GetFileSystemEntries(string path, string searchPattern, global::System.IO.EnumerationOptions enumerationOptions);

        /// <inheritdoc cref="global::System.IO.Directory.EnumerateDirectories"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        global::System.Collections.Generic.IEnumerable<string> EnumerateDirectories(string path);

        /// <inheritdoc cref="global::System.IO.Directory.EnumerateDirectories"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        global::System.Collections.Generic.IEnumerable<string> EnumerateDirectories(string path, string searchPattern);

        /// <inheritdoc cref="global::System.IO.Directory.EnumerateDirectories"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        global::System.Collections.Generic.IEnumerable<string> EnumerateDirectories(string path, string searchPattern, global::System.IO.SearchOption searchOption);

        /// <inheritdoc cref="global::System.IO.Directory.EnumerateDirectories"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        global::System.Collections.Generic.IEnumerable<string> EnumerateDirectories(string path, string searchPattern, global::System.IO.EnumerationOptions enumerationOptions);

        /// <inheritdoc cref="global::System.IO.Directory.EnumerateFiles"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        global::System.Collections.Generic.IEnumerable<string> EnumerateFiles(string path);

        /// <inheritdoc cref="global::System.IO.Directory.EnumerateFiles"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        global::System.Collections.Generic.IEnumerable<string> EnumerateFiles(string path, string searchPattern);

        /// <inheritdoc cref="global::System.IO.Directory.EnumerateFiles"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        global::System.Collections.Generic.IEnumerable<string> EnumerateFiles(string path, string searchPattern, global::System.IO.SearchOption searchOption);

        /// <inheritdoc cref="global::System.IO.Directory.EnumerateFiles"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        global::System.Collections.Generic.IEnumerable<string> EnumerateFiles(string path, string searchPattern, global::System.IO.EnumerationOptions enumerationOptions);

        /// <inheritdoc cref="global::System.IO.Directory.EnumerateFileSystemEntries"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        global::System.Collections.Generic.IEnumerable<string> EnumerateFileSystemEntries(string path);

        /// <inheritdoc cref="global::System.IO.Directory.EnumerateFileSystemEntries"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        global::System.Collections.Generic.IEnumerable<string> EnumerateFileSystemEntries(string path, string searchPattern);

        /// <inheritdoc cref="global::System.IO.Directory.EnumerateFileSystemEntries"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        global::System.Collections.Generic.IEnumerable<string> EnumerateFileSystemEntries(string path, string searchPattern, global::System.IO.SearchOption searchOption);

        /// <inheritdoc cref="global::System.IO.Directory.EnumerateFileSystemEntries"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        global::System.Collections.Generic.IEnumerable<string> EnumerateFileSystemEntries(string path, string searchPattern, global::System.IO.EnumerationOptions enumerationOptions);

        /// <inheritdoc cref="global::System.IO.Directory.GetDirectoryRoot"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        string GetDirectoryRoot(string path);

        /// <inheritdoc cref="global::System.IO.Directory.GetCurrentDirectory"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        string GetCurrentDirectory();

        /// <inheritdoc cref="global::System.IO.Directory.SetCurrentDirectory"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        void SetCurrentDirectory(string path);

        /// <inheritdoc cref="global::System.IO.Directory.Move"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        void Move(string sourceDirName, string destDirName);

        /// <inheritdoc cref="global::System.IO.Directory.Delete"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        void Delete(string path);

        /// <inheritdoc cref="global::System.IO.Directory.Delete"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        void Delete(string path, bool recursive);

        /// <inheritdoc cref="global::System.IO.Directory.GetLogicalDrives"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        string[] GetLogicalDrives();

        /// <inheritdoc cref="global::System.IO.Directory.CreateSymbolicLink"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        global::System.IO.FileSystemInfo CreateSymbolicLink(string path, string pathToTarget);

        /// <inheritdoc cref="global::System.IO.Directory.ResolveLinkTarget"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        global::System.IO.FileSystemInfo? ResolveLinkTarget(string linkPath, bool returnFinalTarget);

    }
}
#pragma warning restore
