//HintName: IDynamic.g.cs
// <auto-generated />
#pragma warning disable
namespace Fluentish.Injectable.MethodReturnTests
{
    /// <inheritdoc cref="global::MethodReturnTests.Dynamic"/>
    public interface IDynamic
    {
        /// <inheritdoc cref="global::MethodReturnTests.Dynamic.Test"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        dynamic Test();

    }
}
#pragma warning restore
