//HintName: Dynamic.g.cs
// <auto-generated />
#pragma warning disable
namespace Fluentish.Injectable.MethodReturnTests
{
    /// <inheritdoc cref="global::MethodReturnTests.Dynamic"/>
    [global::System.Diagnostics.DebuggerStepThrough]
    public class DynamicService : IDynamic
    {
        /// <inheritdoc cref="global::MethodReturnTests.Dynamic.Test"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public dynamic Test()
             => global::MethodReturnTests.Dynamic.Test();
    }
}
#pragma warning restore
