//HintName: IReturnNullableReferenceType.g.cs
// <auto-generated />
#nullable enable
#pragma warning disable
namespace Fluentish.Injectable.FieldReturnTypeTests
{
    /// <inheritdoc cref="global::FieldReturnTypeTests.ReturnNullableReferenceType"/>
    public interface IReturnNullableReferenceType
    {
        /// <inheritdoc cref="global::FieldReturnTypeTests.ReturnNullableReferenceType.Test"/>
        global::FieldReturnTypeTests.Example? Test { get; set; }
    }
}
#pragma warning restore
