//HintName: ReturnNullableReferenceType.g.cs
// <auto-generated />
#nullable enable
#pragma warning disable
namespace Fluentish.Injectable.FieldReturnTypeTests
{
    /// <inheritdoc cref="global::FieldReturnTypeTests.ReturnNullableReferenceType"/>
    [global::System.Diagnostics.DebuggerStepThrough]
    public class ReturnNullableReferenceTypeService : IReturnNullableReferenceType
    {
        /// <inheritdoc cref="global::FieldReturnTypeTests.ReturnNullableReferenceType.Test"/>
        public global::FieldReturnTypeTests.Example? Test
        {
            get => global::FieldReturnTypeTests.ReturnNullableReferenceType.Test;
            set => global::FieldReturnTypeTests.ReturnNullableReferenceType.Test = value;
        }
    }
}
#pragma warning restore
