//HintName: Method.g.cs
// <auto-generated />
#pragma warning disable
namespace Fluentish.Injectable.MemberNameKeywordCollisionTests
{
    /// <inheritdoc cref="global::MemberNameKeywordCollisionTests.Method"/>
    [global::System.Diagnostics.DebuggerStepThrough]
    public class MethodService : IMethod
    {
        /// <inheritdoc cref="global::MemberNameKeywordCollisionTests.Method.@event"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public int @event()
            => global::MemberNameKeywordCollisionTests.Method.@event();

    }
}
#pragma warning restore
