//HintName: IMethod.g.cs
// <auto-generated />
#pragma warning disable
namespace Fluentish.Injectable.MemberNameKeywordCollisionTests
{
    /// <inheritdoc cref="global::MemberNameKeywordCollisionTests.Method"/>
    public interface IMethod
    {
        /// <inheritdoc cref="global::MemberNameKeywordCollisionTests.Method.@event"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        int @event();

    }
}
#pragma warning restore
