//HintName: IInternalEvent.g.cs
// <auto-generated />
#pragma warning disable
namespace Fluentish.Injectable.EventAccessibilityTests
{
    /// <inheritdoc cref="global::EventAccessibilityTests.InternalEvent"/>
    public interface IInternalEvent
    {
    }
}
#pragma warning restore
