//HintName: InternalEvent.g.cs
// <auto-generated />
#pragma warning disable
namespace Fluentish.Injectable.EventAccessibilityTests
{
    /// <inheritdoc cref="global::EventAccessibilityTests.InternalEvent"/>
    [global::System.Diagnostics.DebuggerStepThrough]
    public class InternalEventService: IInternalEvent
    {
    }
}
#pragma warning restore
