//HintName: IGenericTypeConstraintValueType.g.cs
// <auto-generated />
#pragma warning disable
namespace Fluentish.Injectable.GenericTypeTests
{
    /// <inheritdoc cref="global::GenericTypeTests.GenericTypeConstraintValueType<TType>"/>
    public interface IGenericTypeConstraintValueType<TType>
        where TType : struct
    {
        /// <inheritdoc cref="global::GenericTypeTests.GenericTypeConstraintValueType<TType>.Test"/>
        TType Test { get; }

    }
}
#pragma warning restore
