//HintName: CustomPrefix.g.cs
// <auto-generated />
#pragma warning disable
/// <inheritdoc cref="global::NamespaceConstTests.CustomPrefix"/>
[global::System.Diagnostics.DebuggerStepThrough]
public class CustomPrefixService : ICustomPrefix
{
    /// <inheritdoc cref="global::NamespaceConstTests.CustomPrefix.Test"/>
    [global::System.Diagnostics.DebuggerStepThrough]
    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public void Test() => global::NamespaceConstTests.CustomPrefix.Test();
}
#pragma warning restore
