//HintName: IReturnNullableValueType.g.cs
// <auto-generated />
#nullable enable
#pragma warning disable
namespace Fluentish.Injectable.ConstReturnTypeTests
{
    /// <inheritdoc cref="global::ConstReturnTypeTests.ReturnNullableValueType"/>
    public interface IReturnNullableValueType
    {
        /// <inheritdoc cref="global::ConstReturnTypeTests.ReturnNullableValueType.Test"/>
        global::System.Nullable<global::ConstReturnTypeTests.Example> Test { get; }

    }
}
#pragma warning restore
