//HintName: IFunctionPointer.g.cs
// <auto-generated />
#pragma warning disable
namespace Fluentish.Injectable.MethodReturnTests
{
    /// <inheritdoc cref="global::MethodReturnTests.FunctionPointer"/>
    public unsafe interface IFunctionPointer
    {
        /// <inheritdoc cref="global::MethodReturnTests.FunctionPointer.Test"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        delegate*<int, bool> Test();
    }
}
#pragma warning restore
