//HintName: ParameterInPrimitive.g.cs
// <auto-generated />
#pragma warning disable
namespace Fluentish.Injectable.MethodParameterTests
{
    /// <inheritdoc cref="global::MethodParameterTests.ParameterInPrimitive"/>
    [global::System.Diagnostics.DebuggerStepThrough]
    public class ParameterInPrimitiveService : IParameterInPrimitive
    {
        /// <inheritdoc cref="global::MethodParameterTests.ParameterInPrimitive.Test"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public void Test(in int parameter)
             => global::MethodParameterTests.ParameterInPrimitive.Test(in parameter);
    }
}
#pragma warning restore
