//HintName: IParameterInPrimitive.g.cs
// <auto-generated />
#pragma warning disable
namespace Fluentish.Injectable.MethodParameterTests
{
    /// <inheritdoc cref="global::MethodParameterTests.ParameterInPrimitive"/>
    public interface IParameterInPrimitive
    {
        /// <inheritdoc cref="global::MethodParameterTests.ParameterInPrimitive.Test"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        void Test(in int parameter);
    }
}
#pragma warning restore
