//HintName: IGenericType.g.cs
// <auto-generated />
#pragma warning disable
namespace Fluentish.Injectable.GenericTypeTests
{
    /// <inheritdoc cref="global::GenericTypeTests.GenericType<TType>"/>
    public interface IGenericType<TType>
    {
        /// <inheritdoc cref="global::GenericTypeTests.GenericType<TType>.Test"/>
        TType Test { get; }

    }
}
#pragma warning restore
