//HintName: GenericType.g.cs
// <auto-generated />
#pragma warning disable
namespace Fluentish.Injectable.GenericTypeTests
{
    /// <inheritdoc cref="global::GenericTypeTests.GenericType<TType>"/>
    [global::System.Diagnostics.DebuggerStepThrough]
    public class GenericTypeService<TType> : IGenericType<TType>
    {
        /// <inheritdoc cref="global::GenericTypeTests.GenericType<TType>.Test"/>
        public TType Test
        {
            get => global::GenericTypeTests.GenericType<TType>.Test;
        }

    }
}
#pragma warning restore
