//HintName: GenericTypeArgumentConstraintReferenceType.g.cs
// <auto-generated />
#pragma warning disable
namespace Fluentish.Injectable.GenericMethodTests
{
    /// <inheritdoc cref="global::GenericMethodTests.GenericTypeArgumentConstraintReferenceType"/>
    [global::System.Diagnostics.DebuggerStepThrough]
    public class GenericTypeArgumentConstraintReferenceTypeService : IGenericTypeArgumentConstraintReferenceType
    {
        /// <inheritdoc cref="global::GenericMethodTests.GenericTypeArgumentConstraintReferenceType.Test"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public void Test<TType>()
            where TType : class, global::System.IDisposable, new()
             => global::GenericMethodTests.GenericTypeArgumentConstraintReferenceType.Test<TType>();
    }
}
#pragma warning restore
