//HintName: IReturnArray.g.cs
// <auto-generated />
#pragma warning disable
namespace Fluentish.Injectable.PropertyReturnTypeTests
{
    /// <inheritdoc cref="global::PropertyReturnTypeTests.ReturnArray"/>
    public interface IReturnArray
    {
        /// <inheritdoc cref="global::PropertyReturnTypeTests.ReturnArray.Test"/>
        global::PropertyReturnTypeTests.Example[] Test { get; set; }

    }
}
#pragma warning restore
