//HintName: IPublicProperty.g.cs
// <auto-generated />
#pragma warning disable
namespace Fluentish.Injectable.PropertyAccessibilityTests
{
    /// <inheritdoc cref="global::PropertyAccessibilityTests.PublicProperty"/>
    public interface IPublicProperty
    {
        /// <inheritdoc cref="global::PropertyAccessibilityTests.PublicProperty.Test"/>
        int Test { get; set; }

    }
}
#pragma warning restore
