//HintName: PublicProperty.g.cs
// <auto-generated />
#pragma warning disable
namespace Fluentish.Injectable.PropertyAccessibilityTests
{
    /// <inheritdoc cref="global::PropertyAccessibilityTests.PublicProperty"/>
    [global::System.Diagnostics.DebuggerStepThrough]
    public class PublicPropertyService : IPublicProperty
    {
        /// <inheritdoc cref="global::PropertyAccessibilityTests.PublicProperty.Test"/>
        public int Test
        {
            get => global::PropertyAccessibilityTests.PublicProperty.Test;
            set => global::PropertyAccessibilityTests.PublicProperty.Test = value;
        }

    }
}
#pragma warning restore
