//HintName: ReturnNullableReferenceType.g.cs
// <auto-generated />
#nullable enable
#pragma warning disable
namespace Fluentish.Injectable.ConstReturnTypeTests
{
    /// <inheritdoc cref="global::ConstReturnTypeTests.ReturnNullableReferenceType"/>
    [global::System.Diagnostics.DebuggerStepThrough]
    public class ReturnNullableReferenceTypeService : IReturnNullableReferenceType
    {
        /// <inheritdoc cref="global::ConstReturnTypeTests.ReturnNullableReferenceType.Test"/>
        public global::ConstReturnTypeTests.Example? Test
        {
            get => global::ConstReturnTypeTests.ReturnNullableReferenceType.Test;
        }

    }
}
#pragma warning restore
