//HintName: IReturnNullableReferenceType.g.cs
// <auto-generated />
#nullable enable
#pragma warning disable
namespace Fluentish.Injectable.ConstReturnTypeTests
{
    /// <inheritdoc cref="global::ConstReturnTypeTests.ReturnNullableReferenceType"/>
    public interface IReturnNullableReferenceType
    {
        /// <inheritdoc cref="global::ConstReturnTypeTests.ReturnNullableReferenceType.Test"/>
        global::ConstReturnTypeTests.Example? Test { get; }
    }
}
#pragma warning restore
