//HintName: ReturnTuple.g.cs
// <auto-generated />
#pragma warning disable
namespace Fluentish.Injectable.ConstReturnTypeTests
{
    /// <inheritdoc cref="global::ConstReturnTypeTests.ReturnTuple"/>
    [global::System.Diagnostics.DebuggerStepThrough]
    public class ReturnTupleService: IReturnTuple
    {
        /// <inheritdoc cref="global::ConstReturnTypeTests.ReturnTuple.Test"/>
        public global::System.Tuple<string, object> Test
        {
            get => global::ConstReturnTypeTests.ReturnTuple.Test;
        }
    }
}
#pragma warning restore
