//HintName: IReturnTuple.g.cs
// <auto-generated />
#pragma warning disable
namespace Fluentish.Injectable.ConstReturnTypeTests
{
    /// <inheritdoc cref="global::ConstReturnTypeTests.ReturnTuple"/>
    public interface IReturnTuple
    {
        /// <inheritdoc cref="global::ConstReturnTypeTests.ReturnTuple.Test"/>
        global::System.Tuple<string, object> Test { get; }
    }
}
#pragma warning restore
