//HintName: PrivateProperty.g.cs
// <auto-generated />
#pragma warning disable
namespace Fluentish.Injectable.PropertyAccessibilityTests
{
    /// <inheritdoc cref="global::PropertyAccessibilityTests.PrivateProperty"/>
    [global::System.Diagnostics.DebuggerStepThrough]
    public class PrivatePropertyService: IPrivateProperty
    {
    }
}
#pragma warning restore
