//HintName: IPrivateProperty.g.cs
// <auto-generated />
#pragma warning disable
namespace Fluentish.Injectable.PropertyAccessibilityTests
{
    /// <inheritdoc cref="global::PropertyAccessibilityTests.PrivateProperty"/>
    public interface IPrivateProperty
    {
    }
}
#pragma warning restore
