//HintName: IReturnTuple.g.cs
// <auto-generated />
#pragma warning disable
namespace Fluentish.Injectable.PropertyReturnTypeTests
{
    /// <inheritdoc cref="global::PropertyReturnTypeTests.ReturnTuple"/>
    public interface IReturnTuple
    {
        /// <inheritdoc cref="global::PropertyReturnTypeTests.ReturnTuple.Test"/>
        global::System.Tuple<global::PropertyReturnTypeTests.Example, global::PropertyReturnTypeTests.Example> Test { get; set; }

    }
}
#pragma warning restore
