//HintName: GenericTypeConstraintType.g.cs
// <auto-generated />
#pragma warning disable
namespace Fluentish.Injectable.GenericTypeTests
{
    /// <inheritdoc cref="global::GenericTypeTests.GenericTypeConstraintType<TType>"/>
    [global::System.Diagnostics.DebuggerStepThrough]
    public class GenericTypeConstraintTypeService<TType> : IGenericTypeConstraintType<TType>
        where TType : global::System.IDisposable
    {
        /// <inheritdoc cref="global::GenericTypeTests.GenericTypeConstraintType<TType>.Test"/>
        public TType Test
        {
            get => global::GenericTypeTests.GenericTypeConstraintType<TType>.Test;
        }

    }
}
#pragma warning restore
