//HintName: IGenericTypeConstraintType.g.cs
// <auto-generated />
#pragma warning disable
namespace Fluentish.Injectable.GenericTypeTests
{
    /// <inheritdoc cref="global::GenericTypeTests.GenericTypeConstraintType<TType>"/>
    public interface IGenericTypeConstraintType<TType>
        where TType : global::System.IDisposable
    {
        /// <inheritdoc cref="global::GenericTypeTests.GenericTypeConstraintType<TType>.Test"/>
        TType Test { get; }

    }
}
#pragma warning restore
