//HintName: IReturnValueType.g.cs
// <auto-generated />
#pragma warning disable
namespace Fluentish.Injectable.ConstReturnTypeTests
{
    /// <inheritdoc cref="global::ConstReturnTypeTests.ReturnValueType"/>
    public interface IReturnValueType
    {
        /// <inheritdoc cref="global::ConstReturnTypeTests.ReturnValueType.Test"/>
        global::ConstReturnTypeTests.Example Test { get; }

    }
}
#pragma warning restore
