//HintName: ReturnValueType.g.cs
// <auto-generated />
#pragma warning disable
namespace Fluentish.Injectable.ConstReturnTypeTests
{
    /// <inheritdoc cref="global::ConstReturnTypeTests.ReturnValueType"/>
    [global::System.Diagnostics.DebuggerStepThrough]
    public class ReturnValueTypeService: IReturnValueType
    {
        /// <inheritdoc cref="global::ConstReturnTypeTests.ReturnValueType.Test"/>
        public global::ConstReturnTypeTests.Example Test
        {
            get => global::ConstReturnTypeTests.ReturnValueType.Test;
        }

    }
}
#pragma warning restore
