//HintName: ReturnPrimitive.g.cs
// <auto-generated />
#pragma warning disable
namespace Fluentish.Injectable.PropertyReturnTypeTests
{
    /// <inheritdoc cref="global::PropertyReturnTypeTests.ReturnPrimitive"/>
    [global::System.Diagnostics.DebuggerStepThrough]
    public class ReturnPrimitiveService: IReturnPrimitive
    {
        /// <inheritdoc cref="global::PropertyReturnTypeTests.ReturnPrimitive.Test"/>
        public int Test
        {
            get => global::PropertyReturnTypeTests.ReturnPrimitive.Test;
            set => global::PropertyReturnTypeTests.ReturnPrimitive.Test = value;
        }

    }
}
#pragma warning restore
