//HintName: IReturnPrimitive.g.cs
// <auto-generated />
#pragma warning disable
namespace Fluentish.Injectable.PropertyReturnTypeTests
{
    /// <inheritdoc cref="global::PropertyReturnTypeTests.ReturnPrimitive"/>
    public interface IReturnPrimitive
    {
        /// <inheritdoc cref="global::PropertyReturnTypeTests.ReturnPrimitive.Test"/>
        int Test { get; set; }

    }
}
#pragma warning restore
