//HintName: ReferenceType.g.cs
// <auto-generated />
#pragma warning disable
namespace Fluentish.Injectable.MethodReturnTests
{
    /// <inheritdoc cref="global::MethodReturnTests.ReferenceType"/>
    [global::System.Diagnostics.DebuggerStepThrough]
    public class ReferenceTypeService : IReferenceType
    {
        /// <inheritdoc cref="global::MethodReturnTests.ReferenceType.Test"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public global::MethodReturnTests.Example Test() => global::MethodReturnTests.ReferenceType.Test();
    }
}
#pragma warning restore
