//HintName: ReturnArray.g.cs
// <auto-generated />
#pragma warning disable
namespace Fluentish.Injectable.FieldReturnTypeTests
{
    /// <inheritdoc cref="global::FieldReturnTypeTests.ReturnArray"/>
    [global::System.Diagnostics.DebuggerStepThrough]
    public class ReturnArrayService : IReturnArray
    {
        /// <inheritdoc cref="global::FieldReturnTypeTests.ReturnArray.Test"/>
        public global::FieldReturnTypeTests.Example[] Test
        {
            get => global::FieldReturnTypeTests.ReturnArray.Test;
            set => global::FieldReturnTypeTests.ReturnArray.Test = value;
        }

    }
}
#pragma warning restore
