//HintName: IReturnArray.g.cs
// <auto-generated />
#pragma warning disable
namespace Fluentish.Injectable.FieldReturnTypeTests
{
    /// <inheritdoc cref="global::FieldReturnTypeTests.ReturnArray"/>
    public interface IReturnArray
    {
        /// <inheritdoc cref="global::FieldReturnTypeTests.ReturnArray.Test"/>
        global::FieldReturnTypeTests.Example[] Test { get; set; }
    }
}
#pragma warning restore
