//HintName: IReturnReferenceType.g.cs
// <auto-generated />
#pragma warning disable
namespace Fluentish.Injectable.FieldReturnTypeTests
{
    /// <inheritdoc cref="global::FieldReturnTypeTests.ReturnReferenceType"/>
    public interface IReturnReferenceType
    {
        /// <inheritdoc cref="global::FieldReturnTypeTests.ReturnReferenceType.Test"/>
        global::FieldReturnTypeTests.Example Test { get; set; }

    }
}
#pragma warning restore
