//HintName: ReturnReferenceType.g.cs
// <auto-generated />
#pragma warning disable
namespace Fluentish.Injectable.FieldReturnTypeTests
{
    /// <inheritdoc cref="global::FieldReturnTypeTests.ReturnReferenceType"/>
    [global::System.Diagnostics.DebuggerStepThrough]
    public class ReturnReferenceTypeService: IReturnReferenceType
    {
        /// <inheritdoc cref="global::FieldReturnTypeTests.ReturnReferenceType.Test"/>
        public global::FieldReturnTypeTests.Example Test
        {
            get => global::FieldReturnTypeTests.ReturnReferenceType.Test;
            set => global::FieldReturnTypeTests.ReturnReferenceType.Test = value;
        }
    }
}
#pragma warning restore
