//HintName: IGenericTypeConstraintReferenceType.g.cs
// <auto-generated />
#pragma warning disable
namespace Fluentish.Injectable.GenericTypeTests
{
    /// <inheritdoc cref="global::GenericTypeTests.GenericTypeConstraintReferenceType<TType>"/>
    public interface IGenericTypeConstraintReferenceType<TType>
        where TType : class, global::System.IDisposable, new()
    {
        /// <inheritdoc cref="global::GenericTypeTests.GenericTypeConstraintReferenceType<TType>.Test"/>
        TType Test { get; }

    }
}
#pragma warning restore
