//HintName: GenericTypeConstraintReferenceType.g.cs
// <auto-generated />
#pragma warning disable
namespace Fluentish.Injectable.GenericTypeTests
{
    /// <inheritdoc cref="global::GenericTypeTests.GenericTypeConstraintReferenceType<TType>"/>
    [global::System.Diagnostics.DebuggerStepThrough]
    public class GenericTypeConstraintReferenceTypeService<TType> : IGenericTypeConstraintReferenceType<TType>
        where TType : class, global::System.IDisposable, new()
    {
        /// <inheritdoc cref="global::GenericTypeTests.GenericTypeConstraintReferenceType<TType>.Test"/>
        public TType Test
        {
            get => global::GenericTypeTests.GenericTypeConstraintReferenceType<TType>.Test;
        }

    }
}
#pragma warning restore
