//HintName: IEmpty.g.cs
// <auto-generated />
#pragma warning disable
namespace NamespacePrefixTests
{
    /// <inheritdoc cref="global::NamespacePrefixTests.Empty"/>
    public interface IEmpty
    {
        /// <inheritdoc cref="global::NamespacePrefixTests.Empty.Test"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        void Test();
    }
}
#pragma warning restore
