//HintName: IReturnNullableValueType.g.cs
// <auto-generated />
#nullable enable
#pragma warning disable
namespace Fluentish.Injectable.PropertyReturnTypeTests
{
    /// <inheritdoc cref="global::PropertyReturnTypeTests.ReturnNullableValueType"/>
    public interface IReturnNullableValueType
    {
        /// <inheritdoc cref="global::PropertyReturnTypeTests.ReturnNullableValueType.Test"/>
        global::System.Nullable<global::PropertyReturnTypeTests.Example> Test { get; set; }

    }
}
#pragma warning restore
