//HintName: ReturnNullableValueType.g.cs
// <auto-generated />
#nullable enable
#pragma warning disable
namespace Fluentish.Injectable.PropertyReturnTypeTests
{
    /// <inheritdoc cref="global::PropertyReturnTypeTests.ReturnNullableValueType"/>
    [global::System.Diagnostics.DebuggerStepThrough]
    public class ReturnNullableValueTypeService : IReturnNullableValueType
    {
        /// <inheritdoc cref="global::PropertyReturnTypeTests.ReturnNullableValueType.Test"/>
        public global::System.Nullable<global::PropertyReturnTypeTests.Example> Test
        {
            get => global::PropertyReturnTypeTests.ReturnNullableValueType.Test;
            set => global::PropertyReturnTypeTests.ReturnNullableValueType.Test = value;
        }

    }
}
#pragma warning restore
