//HintName: Primitive.g.cs
// <auto-generated />
#pragma warning disable
namespace Fluentish.Injectable.MethodReturnTests
{
    /// <inheritdoc cref="global::MethodReturnTests.Primitive"/>
    [global::System.Diagnostics.DebuggerStepThrough]
    public class PrimitiveService : IPrimitive
    {
        /// <inheritdoc cref="global::MethodReturnTests.Primitive.Test"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public int Test()
             => global::MethodReturnTests.Primitive.Test();
    }
}
#pragma warning restore
