//HintName: IPrimitive.g.cs
// <auto-generated />
#pragma warning disable
namespace Fluentish.Injectable.MethodReturnTests
{
    /// <inheritdoc cref="global::MethodReturnTests.Primitive"/>
    public interface IPrimitive
    {
        /// <inheritdoc cref="global::MethodReturnTests.Primitive.Test"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        int Test();
    }
}
#pragma warning restore
