//HintName: IReturnReferenceType.g.cs
// <auto-generated />
#pragma warning disable
namespace Fluentish.Injectable.ConstReturnTypeTests
{
    /// <inheritdoc cref="global::ConstReturnTypeTests.ReturnReferenceType"/>
    public interface IReturnReferenceType
    {
        /// <inheritdoc cref="global::ConstReturnTypeTests.ReturnReferenceType.Test"/>
        global::ConstReturnTypeTests.Example Test { get; }
    }
}
#pragma warning restore
