//HintName: IGuid.g.cs
// <auto-generated />
#nullable enable
#pragma warning disable
namespace Fluentish.Injectable.System
{
    /// <inheritdoc cref="global::System.Guid"/>
    public interface IGuid
    {
        /// <inheritdoc cref="global::System.Guid.Empty"/>
        global::System.Guid Empty { get; }

        /// <inheritdoc cref="global::System.Guid.Parse"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        global::System.Guid Parse(string input);

        /// <inheritdoc cref="global::System.Guid.Parse"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        global::System.Guid Parse(global::System.ReadOnlySpan<char> input);

        /// <inheritdoc cref="global::System.Guid.TryParse"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        bool TryParse([global::System.Diagnostics.CodeAnalysis.NotNullWhenAttribute(true)] string? input, out global::System.Guid result);

        /// <inheritdoc cref="global::System.Guid.TryParse"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        bool TryParse(global::System.ReadOnlySpan<char> input, out global::System.Guid result);

        /// <inheritdoc cref="global::System.Guid.ParseExact"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        global::System.Guid ParseExact(string input, [global::System.Diagnostics.CodeAnalysis.StringSyntaxAttribute("GuidFormat")] string format);

        /// <inheritdoc cref="global::System.Guid.ParseExact"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        global::System.Guid ParseExact(global::System.ReadOnlySpan<char> input, [global::System.Diagnostics.CodeAnalysis.StringSyntaxAttribute("GuidFormat")] global::System.ReadOnlySpan<char> format);

        /// <inheritdoc cref="global::System.Guid.TryParseExact"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        bool TryParseExact([global::System.Diagnostics.CodeAnalysis.NotNullWhenAttribute(true)] string? input, [global::System.Diagnostics.CodeAnalysis.NotNullWhenAttribute(true), global::System.Diagnostics.CodeAnalysis.StringSyntaxAttribute("GuidFormat")] string? format, out global::System.Guid result);

        /// <inheritdoc cref="global::System.Guid.TryParseExact"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        bool TryParseExact(global::System.ReadOnlySpan<char> input, [global::System.Diagnostics.CodeAnalysis.StringSyntaxAttribute("GuidFormat")] global::System.ReadOnlySpan<char> format, out global::System.Guid result);

        /// <inheritdoc cref="global::System.Guid.Parse"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        global::System.Guid Parse(string s, global::System.IFormatProvider? provider);

        /// <inheritdoc cref="global::System.Guid.TryParse"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        bool TryParse([global::System.Diagnostics.CodeAnalysis.NotNullWhenAttribute(true)] string? s, global::System.IFormatProvider? provider, out global::System.Guid result);

        /// <inheritdoc cref="global::System.Guid.Parse"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        global::System.Guid Parse(global::System.ReadOnlySpan<char> s, global::System.IFormatProvider? provider);

        /// <inheritdoc cref="global::System.Guid.TryParse"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        bool TryParse(global::System.ReadOnlySpan<char> s, global::System.IFormatProvider? provider, out global::System.Guid result);

        /// <inheritdoc cref="global::System.Guid.NewGuid"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        global::System.Guid NewGuid();

    }
}
#pragma warning restore
