//HintName: MultiParameterPrimitive.g.cs
// <auto-generated />
#pragma warning disable
namespace Fluentish.Injectable.MethodParameterTests
{
    /// <inheritdoc cref="global::MethodParameterTests.MultiParameterPrimitive"/>
    [global::System.Diagnostics.DebuggerStepThrough]
    public class MultiParameterPrimitiveService : IMultiParameterPrimitive
    {
        /// <inheritdoc cref="global::MethodParameterTests.MultiParameterPrimitive.Test"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public void Test(int parameter0, int parameter1)
            => global::MethodParameterTests.MultiParameterPrimitive.Test(parameter0, parameter1);

    }
}
#pragma warning restore
