//HintName: IMultiParameterPrimitive.g.cs
// <auto-generated />
#pragma warning disable
namespace Fluentish.Injectable.MethodParameterTests
{
    /// <inheritdoc cref="global::MethodParameterTests.MultiParameterPrimitive"/>
    public interface IMultiParameterPrimitive
    {
        /// <inheritdoc cref="global::MethodParameterTests.MultiParameterPrimitive.Test"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        void Test(int parameter0, int parameter1);

    }
}
#pragma warning restore
