//HintName: IPointer.g.cs
// <auto-generated />
#pragma warning disable
namespace Fluentish.Injectable.MethodReturnTests
{
    /// <inheritdoc cref="global::MethodReturnTests.Pointer"/>
    public unsafe interface IPointer
    {
        /// <inheritdoc cref="global::MethodReturnTests.Pointer.Test"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        int* Test();

    }
}
#pragma warning restore
