//HintName: IGenericTypeArgumentConstraintType.g.cs
// <auto-generated />
#pragma warning disable
namespace Fluentish.Injectable.GenericMethodTests
{
    /// <inheritdoc cref="global::GenericMethodTests.GenericTypeArgumentConstraintType"/>
    public interface IGenericTypeArgumentConstraintType
    {
        /// <inheritdoc cref="global::GenericMethodTests.GenericTypeArgumentConstraintType.Test"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        void Test<TType>()
            where TType : global::System.IDisposable;

    }
}
#pragma warning restore
