//HintName: GenericTypeArgumentConstraintType.g.cs
// <auto-generated />
#pragma warning disable
namespace Fluentish.Injectable.GenericMethodTests
{
    /// <inheritdoc cref="global::GenericMethodTests.GenericTypeArgumentConstraintType"/>
    [global::System.Diagnostics.DebuggerStepThrough]
    public class GenericTypeArgumentConstraintTypeService : IGenericTypeArgumentConstraintType
    {
        /// <inheritdoc cref="global::GenericMethodTests.GenericTypeArgumentConstraintType.Test"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public void Test<TType>()
            where TType : global::System.IDisposable
             => global::GenericMethodTests.GenericTypeArgumentConstraintType.Test<TType>();
    }
}
#pragma warning restore
