//HintName: ReturnPrimitiveArray.g.cs
// <auto-generated />
#pragma warning disable
namespace Fluentish.Injectable.ConstReturnTypeTests
{
    /// <inheritdoc cref="global::ConstReturnTypeTests.ReturnPrimitiveArray"/>
    [global::System.Diagnostics.DebuggerStepThrough]
    public class ReturnPrimitiveArrayService : IReturnPrimitiveArray
    {
        /// <inheritdoc cref="global::ConstReturnTypeTests.ReturnPrimitiveArray.Test"/>
        public object[] Test
        {
            get => global::ConstReturnTypeTests.ReturnPrimitiveArray.Test;
        }
    }
}
#pragma warning restore
