//HintName: IReturnPrimitiveArray.g.cs
// <auto-generated />
#pragma warning disable
namespace Fluentish.Injectable.ConstReturnTypeTests
{
    /// <inheritdoc cref="global::ConstReturnTypeTests.ReturnPrimitiveArray"/>
    public interface IReturnPrimitiveArray
    {
        /// <inheritdoc cref="global::ConstReturnTypeTests.ReturnPrimitiveArray.Test"/>
        object[] Test { get; }

    }
}
#pragma warning restore
