//HintName: IReturnSugarTuple.g.cs
// <auto-generated />
#pragma warning disable
namespace Fluentish.Injectable.FieldReturnTypeTests
{
    /// <inheritdoc cref="global::FieldReturnTypeTests.ReturnSugarTuple"/>
    public interface IReturnSugarTuple
    {
        /// <inheritdoc cref="global::FieldReturnTypeTests.ReturnSugarTuple.Test"/>
        (global::FieldReturnTypeTests.Example left, global::FieldReturnTypeTests.Example right) Test { get; set; }

    }
}
#pragma warning restore
