//HintName: ReturnPrimitiveArray.g.cs
// <auto-generated />
#pragma warning disable
namespace Fluentish.Injectable.FieldReturnTypeTests
{
    /// <inheritdoc cref="global::FieldReturnTypeTests.ReturnPrimitiveArray"/>
    [global::System.Diagnostics.DebuggerStepThrough]
    public class ReturnPrimitiveArrayService: IReturnPrimitiveArray
    {
        /// <inheritdoc cref="global::FieldReturnTypeTests.ReturnPrimitiveArray.Test"/>
        public object[] Test
        {
            get => global::FieldReturnTypeTests.ReturnPrimitiveArray.Test;
            set => global::FieldReturnTypeTests.ReturnPrimitiveArray.Test = value;
        }
    }
}
#pragma warning restore
