//HintName: IReturnPrimitiveArray.g.cs
// <auto-generated />
#pragma warning disable
namespace Fluentish.Injectable.FieldReturnTypeTests
{
    /// <inheritdoc cref="global::FieldReturnTypeTests.ReturnPrimitiveArray"/>
    public interface IReturnPrimitiveArray
    {
        /// <inheritdoc cref="global::FieldReturnTypeTests.ReturnPrimitiveArray.Test"/>
        object[] Test { get; set; }

    }
}
#pragma warning restore
