//HintName: ReturnNullableValueType.g.cs
// <auto-generated />
#nullable enable
#pragma warning disable
namespace Fluentish.Injectable.FieldReturnTypeTests
{
    /// <inheritdoc cref="global::FieldReturnTypeTests.ReturnNullableValueType"/>
    [global::System.Diagnostics.DebuggerStepThrough]
    public class ReturnNullableValueTypeService : IReturnNullableValueType
    {
        /// <inheritdoc cref="global::FieldReturnTypeTests.ReturnNullableValueType.Test"/>
        public global::System.Nullable<global::FieldReturnTypeTests.Example> Test
        {
            get => global::FieldReturnTypeTests.ReturnNullableValueType.Test;
            set => global::FieldReturnTypeTests.ReturnNullableValueType.Test = value;
        }
    }
}
#pragma warning restore
