//HintName: INotDefined.g.cs
// <auto-generated />
#pragma warning disable
namespace Fluentish.Injectable.NamespacePrefixTests
{
    /// <inheritdoc cref="global::NamespacePrefixTests.NotDefined"/>
    public interface INotDefined
    {
        /// <inheritdoc cref="global::NamespacePrefixTests.NotDefined.Test"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        void Test();

    }
}
#pragma warning restore
