//HintName: ParameterOutPrimitive.g.cs
// <auto-generated />
#pragma warning disable
namespace Fluentish.Injectable.MethodParameterTests
{
    /// <inheritdoc cref="global::MethodParameterTests.ParameterOutPrimitive"/>
    [global::System.Diagnostics.DebuggerStepThrough]
    public class ParameterOutPrimitiveService: IParameterOutPrimitive
    {
        /// <inheritdoc cref="global::MethodParameterTests.ParameterOutPrimitive.Test"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public void Test(out int parameter) => global::MethodParameterTests.ParameterOutPrimitive.Test(out parameter);
    }
}
#pragma warning restore
