//HintName: IParameterOutPrimitive.g.cs
// <auto-generated />
#pragma warning disable
namespace Fluentish.Injectable.MethodParameterTests
{
    /// <inheritdoc cref="global::MethodParameterTests.ParameterOutPrimitive"/>
    public interface IParameterOutPrimitive
    {
        /// <inheritdoc cref="global::MethodParameterTests.ParameterOutPrimitive.Test"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        void Test(out int parameter);

    }
}
#pragma warning restore
