//HintName: ReturnPrimitiveArray.g.cs
// <auto-generated />
#pragma warning disable
namespace Fluentish.Injectable.PropertyReturnTypeTests
{
    /// <inheritdoc cref="global::PropertyReturnTypeTests.ReturnPrimitiveArray"/>
    [global::System.Diagnostics.DebuggerStepThrough]
    public class ReturnPrimitiveArrayService : IReturnPrimitiveArray
    {
        /// <inheritdoc cref="global::PropertyReturnTypeTests.ReturnPrimitiveArray.Test"/>
        public object[] Test
        {
            get => global::PropertyReturnTypeTests.ReturnPrimitiveArray.Test;
            set => global::PropertyReturnTypeTests.ReturnPrimitiveArray.Test = value;
        }

    }
}
#pragma warning restore
