//HintName: IParameterParamsPrimitive.g.cs
// <auto-generated />
#pragma warning disable
namespace Fluentish.Injectable.MethodParameterTests
{
    /// <inheritdoc cref="global::MethodParameterTests.ParameterParamsPrimitive"/>
    public interface IParameterParamsPrimitive
    {
        /// <inheritdoc cref="global::MethodParameterTests.ParameterParamsPrimitive.Test"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        void Test(params int[] parameter);
    }
}
#pragma warning restore
