//HintName: IReturnValueType.g.cs
// <auto-generated />
#pragma warning disable
namespace Fluentish.Injectable.FieldReturnTypeTests
{
    /// <inheritdoc cref="global::FieldReturnTypeTests.ReturnValueType"/>
    public interface IReturnValueType
    {
        /// <inheritdoc cref="global::FieldReturnTypeTests.ReturnValueType.Test"/>
        global::FieldReturnTypeTests.Example Test { get; set; }
    }
}
#pragma warning restore
