//HintName: IReturnTuple.g.cs
// <auto-generated />
#pragma warning disable
namespace Fluentish.Injectable.FieldReturnTypeTests
{
    /// <inheritdoc cref="global::FieldReturnTypeTests.ReturnTuple"/>
    public interface IReturnTuple
    {
        /// <inheritdoc cref="global::FieldReturnTypeTests.ReturnTuple.Test"/>
        global::System.Tuple<global::FieldReturnTypeTests.Example, global::FieldReturnTypeTests.Example> Test { get; set; }

    }
}
#pragma warning restore
