//HintName: ReturnTuple.g.cs
// <auto-generated />
#pragma warning disable
namespace Fluentish.Injectable.FieldReturnTypeTests
{
    /// <inheritdoc cref="global::FieldReturnTypeTests.ReturnTuple"/>
    [global::System.Diagnostics.DebuggerStepThrough]
    public class ReturnTupleService : IReturnTuple
    {
        /// <inheritdoc cref="global::FieldReturnTypeTests.ReturnTuple.Test"/>
        public global::System.Tuple<global::FieldReturnTypeTests.Example, global::FieldReturnTypeTests.Example> Test
        {
            get => global::FieldReturnTypeTests.ReturnTuple.Test;
            set => global::FieldReturnTypeTests.ReturnTuple.Test = value;
        }

    }
}
#pragma warning restore
