//HintName: Event.g.cs
// <auto-generated />
#pragma warning disable
namespace Fluentish.Injectable.MemberNameKeywordCollisionTests
{
    /// <inheritdoc cref="global::MemberNameKeywordCollisionTests.Event"/>
    [global::System.Diagnostics.DebuggerStepThrough]
    public class EventService : IEvent
    {
        /// <inheritdoc cref="global::MemberNameKeywordCollisionTests.Event.@event"/>
        public event global::System.EventHandler @event
        {
            add => global::MemberNameKeywordCollisionTests.Event.@event += value;
            remove => global::MemberNameKeywordCollisionTests.Event.@event -= value;
        }

    }
}
#pragma warning restore
