//HintName: IDebug.g.cs
// <auto-generated />
#nullable enable
#pragma warning disable
namespace Fluentish.Injectable.System.Diagnostics
{
    /// <inheritdoc cref="global::System.Diagnostics.Debug"/>
    public interface IDebug
    {
        /// <inheritdoc cref="global::System.Diagnostics.Debug.AutoFlush"/>
        bool AutoFlush { get; set; }

        /// <inheritdoc cref="global::System.Diagnostics.Debug.IndentLevel"/>
        int IndentLevel { get; set; }

        /// <inheritdoc cref="global::System.Diagnostics.Debug.IndentSize"/>
        int IndentSize { get; set; }

        /// <inheritdoc cref="global::System.Diagnostics.Debug.Close"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        void Close();

        /// <inheritdoc cref="global::System.Diagnostics.Debug.Flush"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        void Flush();

        /// <inheritdoc cref="global::System.Diagnostics.Debug.Indent"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        void Indent();

        /// <inheritdoc cref="global::System.Diagnostics.Debug.Unindent"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        void Unindent();

        /// <inheritdoc cref="global::System.Diagnostics.Debug.Print"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        void Print(string? message);

        /// <inheritdoc cref="global::System.Diagnostics.Debug.Print"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        void Print([global::System.Diagnostics.CodeAnalysis.StringSyntaxAttribute("CompositeFormat")] string format, params object?[] args);

        /// <inheritdoc cref="global::System.Diagnostics.Debug.Assert"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        void Assert([global::System.Diagnostics.CodeAnalysis.DoesNotReturnIfAttribute(false)] bool condition);

        /// <inheritdoc cref="global::System.Diagnostics.Debug.Assert"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        void Assert([global::System.Diagnostics.CodeAnalysis.DoesNotReturnIfAttribute(false)] bool condition, string? message);

        /// <inheritdoc cref="global::System.Diagnostics.Debug.Assert"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        void Assert([global::System.Diagnostics.CodeAnalysis.DoesNotReturnIfAttribute(false)] bool condition, ref global::System.Diagnostics.Debug.AssertInterpolatedStringHandler message);

        /// <inheritdoc cref="global::System.Diagnostics.Debug.Assert"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        void Assert([global::System.Diagnostics.CodeAnalysis.DoesNotReturnIfAttribute(false)] bool condition, string? message, string? detailMessage);

        /// <inheritdoc cref="global::System.Diagnostics.Debug.Assert"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        void Assert([global::System.Diagnostics.CodeAnalysis.DoesNotReturnIfAttribute(false)] bool condition, ref global::System.Diagnostics.Debug.AssertInterpolatedStringHandler message, ref global::System.Diagnostics.Debug.AssertInterpolatedStringHandler detailMessage);

        /// <inheritdoc cref="global::System.Diagnostics.Debug.Assert"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        void Assert([global::System.Diagnostics.CodeAnalysis.DoesNotReturnIfAttribute(false)] bool condition, string? message, [global::System.Diagnostics.CodeAnalysis.StringSyntaxAttribute("CompositeFormat")] string detailMessageFormat, params object?[] args);

        /// <inheritdoc cref="global::System.Diagnostics.Debug.Fail"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        [global::System.Diagnostics.CodeAnalysis.DoesNotReturnAttribute()]
        void Fail(string? message);

        /// <inheritdoc cref="global::System.Diagnostics.Debug.Fail"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        [global::System.Diagnostics.CodeAnalysis.DoesNotReturnAttribute()]
        void Fail(string? message, string? detailMessage);

        /// <inheritdoc cref="global::System.Diagnostics.Debug.WriteLine"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        void WriteLine(string? message);

        /// <inheritdoc cref="global::System.Diagnostics.Debug.Write"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        void Write(string? message);

        /// <inheritdoc cref="global::System.Diagnostics.Debug.WriteLine"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        void WriteLine(object? value);

        /// <inheritdoc cref="global::System.Diagnostics.Debug.WriteLine"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        void WriteLine(object? value, string? category);

        /// <inheritdoc cref="global::System.Diagnostics.Debug.WriteLine"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        void WriteLine([global::System.Diagnostics.CodeAnalysis.StringSyntaxAttribute("CompositeFormat")] string format, params object?[] args);

        /// <inheritdoc cref="global::System.Diagnostics.Debug.WriteLine"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        void WriteLine(string? message, string? category);

        /// <inheritdoc cref="global::System.Diagnostics.Debug.Write"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        void Write(object? value);

        /// <inheritdoc cref="global::System.Diagnostics.Debug.Write"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        void Write(string? message, string? category);

        /// <inheritdoc cref="global::System.Diagnostics.Debug.Write"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        void Write(object? value, string? category);

        /// <inheritdoc cref="global::System.Diagnostics.Debug.WriteIf"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        void WriteIf(bool condition, string? message);

        /// <inheritdoc cref="global::System.Diagnostics.Debug.WriteIf"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        void WriteIf(bool condition, ref global::System.Diagnostics.Debug.WriteIfInterpolatedStringHandler message);

        /// <inheritdoc cref="global::System.Diagnostics.Debug.WriteIf"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        void WriteIf(bool condition, object? value);

        /// <inheritdoc cref="global::System.Diagnostics.Debug.WriteIf"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        void WriteIf(bool condition, string? message, string? category);

        /// <inheritdoc cref="global::System.Diagnostics.Debug.WriteIf"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        void WriteIf(bool condition, ref global::System.Diagnostics.Debug.WriteIfInterpolatedStringHandler message, string? category);

        /// <inheritdoc cref="global::System.Diagnostics.Debug.WriteIf"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        void WriteIf(bool condition, object? value, string? category);

        /// <inheritdoc cref="global::System.Diagnostics.Debug.WriteLineIf"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        void WriteLineIf(bool condition, object? value);

        /// <inheritdoc cref="global::System.Diagnostics.Debug.WriteLineIf"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        void WriteLineIf(bool condition, object? value, string? category);

        /// <inheritdoc cref="global::System.Diagnostics.Debug.WriteLineIf"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        void WriteLineIf(bool condition, string? message);

        /// <inheritdoc cref="global::System.Diagnostics.Debug.WriteLineIf"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        void WriteLineIf(bool condition, ref global::System.Diagnostics.Debug.WriteIfInterpolatedStringHandler message);

        /// <inheritdoc cref="global::System.Diagnostics.Debug.WriteLineIf"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        void WriteLineIf(bool condition, string? message, string? category);

        /// <inheritdoc cref="global::System.Diagnostics.Debug.WriteLineIf"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        void WriteLineIf(bool condition, ref global::System.Diagnostics.Debug.WriteIfInterpolatedStringHandler message, string? category);

    }
}
#pragma warning restore
