//HintName: IEventHandler.g.cs
// <auto-generated />
#pragma warning disable
namespace Fluentish.Injectable.EventTests
{
    /// <inheritdoc cref="global::EventTests.EventHandler"/>
    public interface IEventHandler
    {
        /// <inheritdoc cref="global::EventTests.EventHandler.Test"/>
        event global::System.EventHandler Test;

    }
}
#pragma warning restore
