//HintName: INestedGeneric.g.cs
// <auto-generated />
#pragma warning disable
namespace Fluentish.Injectable.MethodReturnTests
{
    /// <inheritdoc cref="global::MethodReturnTests.NestedGeneric"/>
    public interface INestedGeneric
    {
        /// <inheritdoc cref="global::MethodReturnTests.NestedGeneric.Test"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        global::MethodReturnTests.OuterType.InnerType<global::System.DateTime> Test();

    }
}
#pragma warning restore
