//HintName: IValueType.g.cs
// <auto-generated />
#pragma warning disable
namespace Fluentish.Injectable.MethodReturnTests
{
    /// <inheritdoc cref="global::MethodReturnTests.ValueType"/>
    public interface IValueType
    {
        /// <inheritdoc cref="global::MethodReturnTests.ValueType.Test"/>
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        global::MethodReturnTests.Example Test();

    }
}
#pragma warning restore
