//HintName: IReturnArray.g.cs
// <auto-generated />
#pragma warning disable
namespace Fluentish.Injectable.ConstReturnTypeTests
{
    /// <inheritdoc cref="global::ConstReturnTypeTests.ReturnArray"/>
    public interface IReturnArray
    {
        /// <inheritdoc cref="global::ConstReturnTypeTests.ReturnArray.Test"/>
        global::ConstReturnTypeTests.Example[] Test { get; }

    }
}
#pragma warning restore
